In [ ]:
import pandas as pd

player_raw = pd.read_csv("2022-2023 Football Player Stats.csv", delimiter=';', encoding='latin1')

pd.set_option('display.max_columns', None)
print(player_raw.head())

   Rk             Player Nation   Pos         Squad            Comp  Age  \
0   1   Brenden Aaronson    USA  MFFW  Leeds United  Premier League   22
1   2   Yunis Abdelhamid    MAR    DF         Reims         Ligue 1   35
2   3      Himad Abdelli    FRA  MFFW        Angers         Ligue 1   23
3   4  Salis Abdul Samed    GHA    MF          Lens         Ligue 1   22
4   5    Laurent Abergel    FRA    MF       Lorient         Ligue 1   30

   Born  MP  Starts   Min   90s  Goals  Shots   SoT  SoT%  G/Sh  G/SoT  \
0  2000  20      19  1596  17.7      1   1.53  0.28  18.5  0.04   0.20
1  1987  22      22  1980  22.0      0   0.86  0.05   5.3  0.00   0.00
2  1999  14       8   770   8.6      0   1.05  0.35  33.3  0.00   0.00
3  2000  20      20  1799  20.0      1   0.60  0.15  25.0  0.08   0.33
4  1993  15      15  1165  12.9      0   0.31  0.00   0.0  0.00   0.00

   ShoDist  ShoFK  ShoPK  PKatt  PasTotCmp  PasTotAtt  PasTotCmp%  PasTotDist  \
0     19.0   0.11    0.0    0.0       23.2       31.0        74.9       293.0
1     13.5   0.00    0.0    0.0       38.5       47.2        81.5       751.5
2     19.2   0.00    0.0    0.0       40.0       49.5        80.8       676.0
3     20.3   0.00    0.0    0.0       59.5       64.9        91.6       946.3
4     23.9   0.00    0.0    0.0       37.9       43.4        87.3       613.6

   PasTotPrgDist  PasShoCmp  PasShoAtt  PasShoCmp%  PasMedCmp  PasMedAtt  \
0           85.7       13.3       16.2        81.9       5.93       7.74
1          318.5       10.9       12.9        84.5      23.20      25.70
2          188.1       18.5       22.0        84.1      15.50      18.70
3          226.9       29.6       31.8        93.2      24.70      26.20
4          224.7       17.9       19.4        92.4      15.70      17.80

   PasMedCmp%  PasLonCmp  PasLonAtt  PasLonCmp%  Assists  PasAss  Pas3rd  \
0        76.6       0.90       2.37        38.1     0.11    1.75    1.75
1        90.1       3.77       7.00        53.9     0.05    0.27    2.91
2        82.6       4.42       5.93        74.5     0.00    1.51    3.95
3        94.3       3.35       4.30        77.9     0.00    0.50    6.00
4        88.6       2.64       3.95        66.7     0.08    0.62    3.88

    PPA  CrsPA  PasProg  PasAtt  PasLive  PasDead  PasFK    TB    Sw  PasCrs  \
0  0.45   0.11     3.22    31.0     28.1     2.88   0.96  0.17  0.00    2.54
1  0.09   0.00     4.50    47.2     43.3     3.73   3.32  0.00  0.55    0.18
2  1.74   0.35     6.40    49.5     48.1     1.16   0.35  0.12  0.23    1.05
3  0.55   0.10     5.60    64.9     63.1     1.40   1.30  0.05  0.20    0.35
4  0.39   0.00     5.04    43.4     42.6     0.78   0.78  0.39  0.16    0.23

     TI    CK  CkIn  CkOut  CkStr  PasCmp  PasOff  PasBlocks   SCA  \
0  0.23  1.47  0.68   0.62   0.06    23.2    0.00       0.85  3.62
1  0.09  0.00  0.00   0.00   0.00    38.5    0.23       0.59  1.14
2  0.81  0.00  0.00   0.00   0.00    40.0    0.23       1.16  2.67
3  0.10  0.00  0.00   0.00   0.00    59.5    0.35       0.40  1.60
4  0.00  0.00  0.00   0.00   0.00    37.9    0.08       0.31  1.24

   ScaPassLive  ScaPassDead  ScaDrib  ScaSh  ScaFld  ScaDef   GCA  \
0         2.37         0.56     0.23   0.11    0.28    0.06  0.28
1         0.86         0.00     0.00   0.18    0.00    0.09  0.18
2         2.44         0.00     0.00   0.12    0.00    0.12  0.00
3         1.35         0.00     0.10   0.10    0.00    0.05  0.00
4         1.01         0.08     0.00   0.08    0.00    0.08  0.08

   GcaPassLive  GcaPassDead  GcaDrib  GcaSh  GcaFld  GcaDef   Tkl  TklWon  \
0         0.17          0.0      0.0   0.06     0.0    0.06  1.64    0.51
1         0.14          0.0      0.0   0.05     0.0    0.00  2.50    1.59
2         0.00          0.0      0.0   0.00     0.0    0.00  2.91    1.40
3         0.00          0.0      0.0   0.00     0.0    0.00  1.50    0.80
4         0.08          0.0      0.0   0.00     0.0    0.00  3.80    2.02

   TklDef3rd  TklMid3rd  TklAtt3rd  TklDri  TklDriAtt  TklDri%  TklDriPast  \
0       0.45       0.90       0.28    0.51       1.47     34.6        0.96
1       1.45       1.00       0.05    1.32       1.68     78.4        0.36
2       1.28       1.40       0.23    1.63       2.67     60.9        1.05
3       0.55       0.85       0.10    0.85       1.30     65.4        0.45
4       2.64       1.16       0.00    1.32       3.26     40.5        1.94

   Blocks  BlkSh  BlkPass   Int  Tkl+Int   Clr   Err  Touches  TouDefPen  \
0    1.69   0.11     1.58  0.06     1.69  0.28  0.06     44.0       0.40
1    2.23   0.77     1.45  2.00     4.50  2.91  0.05     59.2       6.23
2    1.51   0.12     1.40  0.93     3.84  0.93  0.00     62.6       0.93
3    1.30   0.35     0.95  1.10     2.60  0.80  0.00     73.3       2.10
4    1.40   0.23     1.16  1.16     4.96  1.55  0.00     54.7       3.26

   TouDef3rd  TouMid3rd  TouAtt3rd  TouAttPen  TouLive  ToAtt  ToSuc  ToSuc%  \
0       4.35       19.0      21.50       2.49     44.0   3.73   1.19    31.8
1      27.50       29.5       2.73       1.09     59.2   0.68   0.32    46.7
2      11.40       36.0      17.40       1.16     62.6   3.84   2.09    54.5
3      12.00       49.6      12.20       0.70     73.3   1.25   0.70    56.0
4      19.20       31.4       4.88       0.23     54.7   0.93   0.54    58.3

   ToTkl  ToTkl%  Carries  CarTotDist  CarPrgDist  CarProg  Car3rd   CPA  \
0   1.75    47.0     26.7       136.1        56.6     1.53    1.07  0.40
1   0.36    53.3     40.0       234.2       125.0     0.55    0.23  0.09
2   1.51    39.4     48.5       298.5       151.0     2.56    2.56  0.47
3   0.40    32.0     61.0       316.9       117.5     1.25    1.95  0.15
4   0.31    33.3     41.0       174.3        72.7     0.47    0.93  0.00

   CarMis  CarDis   Rec  RecProg  CrdY  CrdR  2CrdY   Fls   Fld   Off   Crs  \
0    2.60    3.11  30.2     5.65  0.11   0.0    0.0  0.62  2.26  0.17  2.54
1    0.73    0.68  34.5     0.23  0.09   0.0    0.0  1.32  0.50  0.05  0.18
2    2.09    1.05  43.4     5.93  0.12   0.0    0.0  1.74  1.28  0.00  1.05
3    1.35    1.30  56.5     1.70  0.15   0.0    0.0  2.45  1.35  0.00  0.35
4    1.32    0.78  36.4     0.47  0.16   0.0    0.0  0.93  1.01  0.00  0.23

   TklW  PKwon  PKcon    OG  Recov  AerWon  AerLost  AerWon%
0  0.51    0.0    0.0  0.00   4.86    0.34     1.19     22.2
1  1.59    0.0    0.0  0.00   6.64    2.18     1.23     64.0
2  1.40    0.0    0.0  0.00   8.14    0.93     1.05     47.1
3  0.80    0.0    0.0  0.05   6.60    0.50     0.50     50.0
4  2.02    0.0    0.0  0.00   6.51    0.31     0.39     44.4

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# Your list of player names
# player_list = ["Brenden Aaronson", "Yunis Abdelhamid", "Himad Abdelli"]
player_list = player_raw['Player'].unique()
# player_list = ['Yunis Abdelhamid']

# Base URL for player search
base_url = "https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query="

# DataFrame to store results
results = []

# Total number of players
total_players = len(player_list)

# Iterate through the player list with a counter
for i, player in enumerate(player_list, start=1):
    # Format the player name for the URL
    search_url = base_url + player.replace(" ", "+")
    print(f"Processing player {i}/{total_players}: {player}")

    try:
        # Fetch the page
        response = requests.get(search_url, headers={"User-Agent": "Mozilla/5.0"})
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        # Extract the market value
        market_value_tag = soup.find("td", class_="rechts hauptlink")  # Target the specific class
        if market_value_tag:
            market_value = market_value_tag.text.strip()
        else:
            market_value = "Not Found"

        # Append the result
        results.append({"Player": player, "Market Value": market_value})
    except Exception as e:
        results.append({"Player": player, "Market Value": "Error: " + str(e)})

    # Pause to avoid being blocked by the website
    time.sleep(2)

# Convert results to DataFrame
df_results = pd.DataFrame(results)

# Display or save the DataFrame
#print(df_results)
df_results.to_csv("player_market_values.csv", index=False)
print("scrapping completed")
# Website: https://www.transfermarkt.com/

Processing player 1/2530: Brenden Aaronson
Processing player 2/2530: Yunis Abdelhamid
Processing player 3/2530: Himad Abdelli
Processing player 4/2530: Salis Abdul Samed
Processing player 5/2530: Laurent Abergel
Processing player 6/2530: Oliver Abildgaard
Processing player 7/2530: Matthis Abline
Processing player 8/2530: Abner
Processing player 9/2530: Zakaria Aboukhlal
Processing player 10/2530: Tammy Abraham
Processing player 11/2530: Francesco Acerbi
Processing player 12/2530: Mohamed Achi
Processing player 13/2530: Marcos Acuña
Processing player 14/2530: Che Adams
Processing player 15/2530: Tyler Adams
Processing player 16/2530: Sargis Adamyan
Processing player 17/2530: Tosin Adarabioyo
Processing player 18/2530: Martin Adeline
Processing player 19/2530: Karim Adeyemi
Processing player 20/2530: Amine Adli
Processing player 21/2530: Yacine Adli
Processing player 22/2530: Michel Aebischer
Processing player 23/2530: Felix Afena-Gyan
Processing player 24/2530: Emmanuel Agbadou
Processing player 25/2530: Lucien Agoume
Processing player 26/2530: Felix Agu
Processing player 27/2530: Álvaro Aguado
Processing player 28/2530: Kevin Agudelo
Processing player 29/2530: Nayef Aguerd
Processing player 30/2530: Ruben Aguilar
Processing player 31/2530: Naouirou Ahamada
Processing player 32/2530: Amar Ahmed
Processing player 33/2530: Jean-Eudes Aholou
Processing player 34/2530: Joseph Aidoo
Processing player 35/2530: Ola Aina
Processing player 36/2530: Rayan Aït Nouri
Processing player 37/2530: Emanuel Aiwum
Processing player 38/2530: Kristoffer Ajer
Processing player 39/2530: Ludovic Ajorque
Processing player 40/2530: Manuel Akanji
Processing player 41/2530: Nathan Aké
Processing player 42/2530: Sergio Akieme
Processing player 43/2530: Maghnes Akliouche
Processing player 44/2530: Paul Akouokou
Processing player 45/2530: Jean-Daniel Akpa-Akpro
Processing player 46/2530: Kevin Akpoguma
Processing player 47/2530: David Alaba
Processing player 48/2530: Tomás Alarcón
Processing player 49/2530: Lucas Alario
Processing player 50/2530: Jordi Alba
Processing player 51/2530: Luis Alberto
Processing player 52/2530: Raúl Albiol
Processing player 53/2530: Marc Albrighton
Processing player 54/2530: Thiago Alcántara
Processing player 55/2530: Carlos Alcaraz
Processing player 56/2530: Rubén Alcaraz
Processing player 57/2530: Omar Alderete
Processing player 58/2530: Iván Alejo
Processing player 59/2530: Doðan Alemdar
Processing player 60/2530: Carles Aleñá
Processing player 61/2530: Trent Alexander-Arnold
Processing player 62/2530: Alejandro Alfaro
Processing player 63/2530: Ángel Algobia
Processing player 64/2530: Mohamed Ali Cho
Processing player 65/2530: Faride Alidou
Processing player 66/2530: Alisson
Processing player 67/2530: Jim Allevinah
Processing player 68/2530: Dele Alli
Processing player 69/2530: Domingos André Ribeiro Almeida
Processing player 70/2530: Miguel Almirón
Processing player 71/2530: Marcos Alonso
Processing player 72/2530: Mickaël Alphonse
Processing player 73/2530: Éder Álvarez Balanta
Processing player 74/2530: Carlos Álvarez
Processing player 75/2530: Gastón Álvarez
Processing player 76/2530: Julián Álvarez
Processing player 77/2530: Agustín Álvarez Martínez
Processing player 78/2530: Yeray Álvarez
Processing player 79/2530: Ibrahim Amadou
Processing player 80/2530: Daniel Amartey
Processing player 81/2530: Amath
Processing player 82/2530: Jordan Amavi
Processing player 83/2530: Kelvin Amian
Processing player 84/2530: Bruno Amione
Processing player 85/2530: Nadiem Amiri
Processing player 86/2530: Ethan Ampadu
Processing player 87/2530: Sofyan Amrabat
Processing player 88/2530: Joachim Andersen
Processing player 89/2530: Elliot Anderson
Processing player 90/2530: Felipe Anderson
Processing player 91/2530: Benjamin André
Processing player 92/2530: Komnen Andri?
Processing player 93/2530: Robert Andrich
Processing player 94/2530: Angeliño
Processing player 95/2530: Fabrizio Angileri
Processing player 96/2530: Jaidon Anthony
Processing player 97/2530: Janis Antiste
Processing player 98/2530: Waldemar Anton
Processing player 99/2530: Marcos Antônio
Processing player 100/2530: Michail Antonio
Processing player 101/2530: Antony
Processing player 102/2530: Valentin Antov
Processing player 103/2530: Christopher Antwi-Adjei
Processing player 104/2530: Anuar
Processing player 105/2530: Houssem Aouar
Processing player 106/2530: Adil Aouchiche
Processing player 107/2530: Dennis Appiah
Processing player 108/2530: Mauro Arambarri
Processing player 109/2530: Charles Aránguiz
Processing player 110/2530: Ronald Araújo
Processing player 111/2530: Cameron Archer
Processing player 112/2530: Taïryk Arconte
Processing player 113/2530: Alphonse Areola
Processing player 114/2530: Joe Aribo
Processing player 115/2530: Adam Armstrong
Processing player 116/2530: Stuart Armstrong
Processing player 117/2530: Marko Arnautovi?
Processing player 118/2530: Maximilian Arnold
Processing player 119/2530: Kepa Arrizabalaga
Processing player 120/2530: Roberto Arroyo
Processing player 121/2530: Tolgay Arslan
Processing player 122/2530: Arthur
Processing player 123/2530: Santiago Arzamendia
Processing player 124/2530: Takuma Asano
Processing player 125/2530: Santiago Ascacíbar
Processing player 126/2530: Sergio Asenjo
Processing player 127/2530: Marco Asensio
Processing player 128/2530: Kristoffer Askildsen
Processing player 129/2530: Fisnik Asllani
Processing player 130/2530: Kristjan Asllani
Processing player 131/2530: Iago Aspas
Processing player 132/2530: Lorenz Assignon
Processing player 133/2530: Youcef Atal
Processing player 134/2530: Pierre-Emerick Aubameyang
Processing player 135/2530: Emil Audero
Processing player 136/2530: Tommaso Augello
Processing player 137/2530: Ludwig Augustinsson
Processing player 138/2530: Serge Aurier
Processing player 139/2530: Mathias Autret
Processing player 140/2530: Ezequiel Ávila
Processing player 141/2530: Cédric Avinel
Processing player 142/2530: Taiwo Awoniyi
Processing player 143/2530: Mehmet-Can Aydin
Processing player 144/2530: André Ayew
Processing player 145/2530: Jordan Ayew
Processing player 146/2530: Kaan Ayhan
Processing player 147/2530: Luke Ayling
Processing player 148/2530: Ayman Azhil
Processing player 149/2530: Sardar Azmoun
Processing player 150/2530: César Azpilicueta
Processing player 151/2530: Sanoussy Ba
Processing player 152/2530: Iddrisu Baba
Processing player 153/2530: Sr?an Babi?
Processing player 154/2530: Loïc Bade
Processing player 155/2530: Édgar Badía
Processing player 156/2530: Benoît Badiashile
Processing player 157/2530: Alex Baena
Processing player 158/2530: Jaime Báez
Processing player 159/2530: Leon Bailey
Processing player 160/2530: Eric Bailly
Processing player 161/2530: Dénys Bain
Processing player 162/2530: Brandon Baiye
Processing player 163/2530: Stefan Bajcetic
Processing player 164/2530: Nedim Bajrami
Processing player 165/2530: Cédric Bakambu
Processing player 166/2530: Mitchel Bakker
Processing player 167/2530: Ridle Baku
Processing player 168/2530: Tommaso Baldanzi
Processing player 169/2530: Alejandro Balde
Processing player 170/2530: Thierno Balde
Processing player 171/2530: Carlos Baleba
Processing player 172/2530: Mikel Balenziaga
Processing player 173/2530: Leonardo Balerdi
Processing player 174/2530: Iván Balliu
Processing player 175/2530: Fodé Ballo-Touré
Processing player 176/2530: Folarin Balogun
Processing player 177/2530: Abdoulaye Bamba
Processing player 178/2530: Jonathan Bamba
Processing player 179/2530: Patrick Bamford
Processing player 180/2530: Lameck Banda
Processing player 181/2530: Filippo Bandinelli
Processing player 182/2530: Léo Baptistão
Processing player 183/2530: Shandon Baptiste
Processing player 184/2530: Antonín Barák
Processing player 185/2530: Andrea Barberis
Processing player 186/2530: Bradley Barcola
Processing player 187/2530: Melvin Bard
Processing player 188/2530: Keidi Bare
Processing player 189/2530: Nicolò Barella
Processing player 190/2530: Kike Barja
Processing player 191/2530: Ross Barkley
Processing player 192/2530: Aymen Barkok
Processing player 193/2530: Harvey Barnes
Processing player 194/2530: Leandro Barreiro Martins
Processing player 195/2530: Ander Barrenetxea
Processing player 196/2530: Mickaël Barreto
Processing player 197/2530: Pablo Barrios
Processing player 198/2530: Musa Barrow
Processing player 199/2530: Federico Baschirotto
Processing player 200/2530: Toma Bai?
Processing player 201/2530: Gil Bastião Dias
Processing player 202/2530: Alessandro Bastoni
Processing player 203/2530: Simone Bastoni
Processing player 204/2530: Rodrigo Battaglia
Processing player 205/2530: Maximilian Bauer
Processing player 206/2530: Oliver Baumann
Processing player 207/2530: Timo Baumgartl
Processing player 208/2530: Julian Baumgartlinger
Processing player 209/2530: Christoph Baumgartner
Processing player 210/2530: Cyrille Bayala
Processing player 211/2530: Brian Bayeye
Processing player 212/2530: Noah Joel Sarenren Bazee
Processing player 213/2530: Gavin Bazunu
Processing player 214/2530: Bebé
Processing player 215/2530: Ihlas Bebou
Processing player 216/2530: Rodrigo Becão
Processing player 217/2530: Mads Bech Sørensen
Processing player 218/2530: Julius Beck
Processing player 219/2530: Sheraldo Becker
Processing player 220/2530: Jan Bednarek
Processing player 221/2530: Donny van de Beek
Processing player 222/2530: Asmir Begovi?
Processing player 223/2530: Yanis Begraoui
Processing player 224/2530: Kevin Behrens
Processing player 225/2530: Alexis Beka Beka
Processing player 226/2530: Jérémie Bela
Processing player 227/2530: Youcef Belaïli
Processing player 228/2530: Haris Belkebla
Processing player 229/2530: Stefan Bell
Processing player 230/2530: Armel Bella Kotchap
Processing player 231/2530: Raoul Bellanova
Processing player 232/2530: Karim Bellarabi
Processing player 233/2530: Jean-Ricner Bellegarde
Processing player 234/2530: Héctor Bellerín
Processing player 235/2530: Jude Bellingham
Processing player 236/2530: Jeanöel Belocian
Processing player 237/2530: Andrea Belotti
Processing player 238/2530: Fran Beltrán
Processing player 239/2530: Eliesse Ben Seghir
Processing player 240/2530: Salim Ben Seghir
Processing player 241/2530: Wissam Ben Yedder
Processing player 242/2530: Marco Benassi
Processing player 243/2530: Ismaël Bennacer
Processing player 244/2530: Saïd Benrahma
Processing player 245/2530: Ramy Bensebaini
Processing player 246/2530: Nabil Bentaleb
Processing player 247/2530: Rodrigo Bentancur
Processing player 248/2530: Karim Benzema
Processing player 249/2530: Domenico Berardi
Processing player 250/2530: Yuri Berchiche
Processing player 251/2530: Álex Berenguer
Processing player 252/2530: Bartosz Bereszy?ski
Processing player 253/2530: Patrick Berg
Processing player 254/2530: Mitchell van Bergen
Processing player 255/2530: Mergim Berisha
Processing player 256/2530: Quentin Bernard
Processing player 257/2530: Paul Bernardoni
Processing player 258/2530: Juan Bernat
Processing player 259/2530: Victor Bernth Kristiansen
Processing player 260/2530: Jason Berthomier
Processing player 261/2530: Beto
Processing player 262/2530: Owen Bevan
Processing player 263/2530: Matteo Bianchetti
Processing player 264/2530: Alessandro Bianco
Processing player 265/2530: Giulian Biancone
Processing player 266/2530: Ermin Bi?ak?i?
Processing player 267/2530: Pedro Bigas
Processing player 268/2530: Jaka Bijol
Processing player 269/2530: El Bilal Touré
Processing player 270/2530: Philip Billing
Processing player 271/2530: Jean-Claude Billong
Processing player 272/2530: Cristiano Biraghi
Processing player 273/2530: Samuele Birindelli
Processing player 274/2530: Veljko Birman?evi?
Processing player 275/2530: Tom Bischof
Processing player 276/2530: Yves Bissouma
Processing player 277/2530: Kristijan Bistrovi?
Processing player 278/2530: Leonardo Bittencourt
Processing player 279/2530: Marco Bizot
Processing player 280/2530: Blanco
Processing player 281/2530: Lautaro Blanco
Processing player 282/2530: Rubén Blanco
Processing player 283/2530: Ludovic Blas
Processing player 284/2530: Janis Blaswich
Processing player 285/2530: Miha Bla?i?
Processing player 286/2530: Joaquín Blázquez
Processing player 287/2530: Alexis Blin
Processing player 288/2530: Daley Blind
Processing player 289/2530: Myron Boadu
Processing player 290/2530: Jérôme Boateng
Processing player 291/2530: Kevin-Prince Boateng
Processing player 292/2530: Antonin Bobichon
Processing player 293/2530: Jean-Paul Boëtius
Processing player 294/2530: Jeremie Boga
Processing player 295/2530: Emil Bohinen
Processing player 296/2530: Quentin Boisgard
Processing player 297/2530: Willy Boly
Processing player 298/2530: Giacomo Bonaventura
Processing player 299/2530: Federico Bonazzoli
Processing player 300/2530: Warren Bondo
Processing player 301/2530: Theo Bongonda
Processing player 302/2530: Kevin Bonifazi
Processing player 303/2530: Leonardo Bonucci
Processing player 304/2530: Neto Borges
Processing player 305/2530: Yvandro Borges Sanches
Processing player 306/2530: Sebastiaan Bornauw
Processing player 307/2530: Rafael Borré
Processing player 308/2530: Erik Botheim
Processing player 309/2530: Sven Botman
Processing player 310/2530: Kenji-Van Boto
Processing player 311/2530: Kouamé Botué
Processing player 312/2530: Badredine Bouanani
Processing player 313/2530: Hicham Boudaoui
Processing player 314/2530: Franci Bouebari
Processing player 315/2530: Sofiane Boufal
Processing player 316/2530: Wassim Boullif
Processing player 317/2530: Yassine Bounou
Processing player 318/2530: Ismaëlben Boura
Processing player 319/2530: Mehdi Bourabia
Processing player 320/2530: Benjamin Bourigeaud
Processing player 321/2530: Edoardo Bove
Processing player 322/2530: Jarrod Bowen
Processing player 323/2530: Lucas Boyé
Processing player 324/2530: Jayden Braaf
Processing player 325/2530: Domagoj Bradari?
Processing player 326/2530: Bilal Brahimi
Processing player 327/2530: Martin Braithwaite
Processing player 328/2530: Juan Brandáriz
Processing player 329/2530: Julian Brandt
Processing player 330/2530: Darko Braanac
Processing player 331/2530: Lilian Brassier
Processing player 332/2530: Claudio Bravo
Processing player 333/2530: Fabian Bredlow
Processing player 334/2530: James Bree
Processing player 335/2530: Josip Brekalo
Processing player 336/2530: Gleison Bremer
Processing player 337/2530: Armando Broja
Processing player 338/2530: Dylan Bronn
Processing player 339/2530: John Brooks
Processing player 340/2530: Moritz Broschinski
Processing player 341/2530: Marcelo Brozovi?
Processing player 342/2530: Cédric Brunner
Processing player 343/2530: Lewis Brunt
Processing player 344/2530: Jacob Bruun Larsen
Processing player 345/2530: Andreas Bruus
Processing player 346/2530: Bryan
Processing player 347/2530: Joe Bryan
Processing player 348/2530: Lee Buchanan
Processing player 349/2530: Ante Budimir
Processing player 350/2530: Emi Buendía
Processing player 351/2530: Hugo Bueno
Processing player 352/2530: Santiago Bueno
Processing player 353/2530: Adam Buksa
Processing player 354/2530: Marius Bülter
Processing player 355/2530: Cristian Buonaiuto
Processing player 356/2530: Facundo Buonanotte
Processing player 357/2530: Alessandro Buongiorno
Processing player 358/2530: Delano Burgzorg
Processing player 359/2530: Jonathan Burkardt
Processing player 360/2530: Oliver Burke
Processing player 361/2530: Dan Burn
Processing player 362/2530: Maxime Busi
Processing player 363/2530: Sergio Busquets
Processing player 364/2530: Aurélio Buta
Processing player 365/2530: Marcin Bu?ka
Processing player 366/2530: Jamie Bynoe-Gittens
Processing player 367/2530: Juan Cabal
Processing player 368/2530: Rémy Cabella
Processing player 369/2530: Jimmy Cabot
Processing player 370/2530: Leandro Cabrera
Processing player 371/2530: Liberato Cacace
Processing player 372/2530: Anthony Caci
Processing player 373/2530: Cafú
Processing player 374/2530: Moisés Caicedo
Processing player 375/2530: Tom Cairney
Processing player 376/2530: Jens Cajuste
Processing player 377/2530: Cala
Processing player 378/2530: Davide Calabria
Processing player 379/2530: Mattia Caldara
Processing player 380/2530: Luca Caldirola
Processing player 381/2530: Fernando Calero
Processing player 382/2530: Duje ?aleta-Car
Processing player 383/2530: Hakan Çalhanoðlu
Processing player 384/2530: Kerim Calhanoglu
Processing player 385/2530: Daniel Caligiuri
Processing player 386/2530: Alexander Callens
Processing player 387/2530: Dominic Calvert-Lewin
Processing player 388/2530: Mahdi Camara
Processing player 389/2530: Mohamed Camara
Processing player 390/2530: Ousmane Camara
Processing player 391/2530: Eduardo Camavinga
Processing player 392/2530: Nicolò Cambiaghi
Processing player 393/2530: Andrea Cambiaso
Processing player 394/2530: Axel Camblan
Processing player 395/2530: Sergio Camello
Processing player 396/2530: Chem Campbell
Processing player 397/2530: Emre Can
Processing player 398/2530: Sergio Canales
Processing player 399/2530: Matteo Cancellieri
Processing player 400/2530: João Cancelo
Processing player 401/2530: Antonio Candreva
Processing player 402/2530: Thomas Cannon
Processing player 403/2530: Sergi Canós
Processing player 404/2530: Ander Capa
Processing player 405/2530: Pierrick Capelle
Processing player 406/2530: Étienne Capoue
Processing player 407/2530: Gianluca Caprari
Processing player 408/2530: Francesco Caputo
Processing player 409/2530: Maxence Caqueret
Processing player 410/2530: Andrea Carboni
Processing player 411/2530: Valentin Carboni
Processing player 412/2530: Isaac Carcelen
Processing player 413/2530: Irvin Cardona
Processing player 414/2530: Igor Carioca
Processing player 415/2530: Carlos
Processing player 416/2530: Diego Carlos
Processing player 417/2530: Juan Carlos
Processing player 418/2530: José Carlos Lazo
Processing player 419/2530: Carmona
Processing player 420/2530: Marco Carnesecchi
Processing player 421/2530: Yannick Carrasco
Processing player 422/2530: Dani Carvajal
Processing player 423/2530: Fabio Carvalho
Processing player 424/2530: Matis Carvalho
Processing player 425/2530: William Carvalho
Processing player 426/2530: Nicolò Casale
Processing player 427/2530: Casemiro
Processing player 428/2530: Matty Cash
Processing player 429/2530: Timothy Castagne
Processing player 430/2530: Michele Castagnetti
Processing player 431/2530: Koen Casteels
Processing player 432/2530: Valentín Castellanos
Processing player 433/2530: Jean-Charles Castelletto
Processing player 434/2530: Samu Castillejo
Processing player 435/2530: Jonny Castro
Processing player 436/2530: Gaetano Castrovilli
Processing player 437/2530: Danilo Cataldi
Processing player 438/2530: Catena
Processing player 439/2530: Yoann Cathline
Processing player 440/2530: Maximiliano Caufriez
Processing player 441/2530: Edinson Cavani
Processing player 442/2530: Dani Ceballos
Processing player 443/2530: Federico Ceccherini
Processing player 444/2530: Assan Ceesay
Processing player 445/2530: Emil Ceide
Processing player 446/2530: Zeki Çelik
Processing player 447/2530: Fabien Centonze
Processing player 448/2530: Franco Cervi
Processing player 449/2530: Julio César Enciso
Processing player 450/2530: Leonardo César Jardim
Processing player 451/2530: Julian Chabot
Processing player 452/2530: Florian Chabrolle
Processing player 453/2530: El Chadaille Bitshiabu
Processing player 454/2530: Fares Chaïbi
Processing player 455/2530: Nathaniel Chalobah
Processing player 456/2530: Trevoh Chalobah
Processing player 457/2530: Calum Chambers
Processing player 458/2530: Timothy Chandler
Processing player 459/2530: Gaëtan Charbonnier
Processing player 460/2530: Brendan Chardonnet
Processing player 461/2530: Xavier Chavalerin
Processing player 462/2530: Pep Chavarría
Processing player 463/2530: Rayan Cherki
Processing player 464/2530: Ilyes Cheti
Processing player 465/2530: Lucas Chevalier
Processing player 466/2530: Fabio Chiarodia
Processing player 467/2530: Federico Chiesa

In [ ]:
# Loading the data back in
df_results_2 = pd.read_csv("player_market_values.csv")

# Removing the data that we could not pull Market Value
df_results_2 = df_results_2[df_results_2['Market Value'] != 'Not Found']
df_results_2 = df_results_2[df_results_2['Market Value'] != '-']

# Converting the Ks and Ms to actual Numbers

# Conversion function
def convert_market_value(value):
    value = value.replace("€", "").replace(",", "").strip()  # Remove currency symbol and commas
    if "m" in value:
        return float(value.replace("m", "")) * 1_000_000  # Convert millions to numeric
    elif "k" in value:
        return float(value.replace("k", "")) * 1_000  # Convert thousands to numeric
    else:
        return float(value)  # Return the number as-is if no unit

# Apply the conversion
df_results_2["Market Value Euros"] = df_results_2["Market Value"].apply(convert_market_value)

# Joining the Market Value to the Main DF
print(player_raw.shape)
player_raw = player_raw.merge(df_results_2, how = 'left', on = 'Player')
print(player_raw.shape)

# filtering out players that we don't have market value
player_raw = player_raw[~player_raw['Market Value Euros'].isna()]
print(player_raw.shape)
player_raw.head()

(2689, 124)
(2689, 126)
(2415, 126)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,90s,Goals,Shots,SoT,SoT%,G/Sh,G/SoT,ShoDist,ShoFK,ShoPK,PKatt,PasTotCmp,PasTotAtt,PasTotCmp%,PasTotDist,PasTotPrgDist,PasShoCmp,PasShoAtt,PasShoCmp%,PasMedCmp,PasMedAtt,PasMedCmp%,PasLonCmp,PasLonAtt,PasLonCmp%,Assists,PasAss,Pas3rd,PPA,CrsPA,PasProg,PasAtt,PasLive,PasDead,PasFK,TB,Sw,PasCrs,TI,CK,CkIn,CkOut,CkStr,PasCmp,PasOff,PasBlocks,SCA,ScaPassLive,ScaPassDead,ScaDrib,ScaSh,ScaFld,ScaDef,GCA,GcaPassLive,GcaPassDead,GcaDrib,GcaSh,GcaFld,GcaDef,Tkl,TklWon,TklDef3rd,TklMid3rd,TklAtt3rd,TklDri,TklDriAtt,TklDri%,TklDriPast,Blocks,BlkSh,BlkPass,Int,Tkl+Int,Clr,Err,Touches,TouDefPen,TouDef3rd,TouMid3rd,TouAtt3rd,TouAttPen,TouLive,ToAtt,ToSuc,ToSuc%,ToTkl,ToTkl%,Carries,CarTotDist,CarPrgDist,CarProg,Car3rd,CPA,CarMis,CarDis,Rec,RecProg,CrdY,CrdR,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%,Market Value,Market Value Euros
0,1,Brenden Aaronson,USA,MFFW,Leeds United,Premier League,22,2000,20,19,1596,17.7,1,1.53,0.28,18.5,0.04,0.20,19.0,0.11,0.0,0.0,23.2,31.0,74.9,293.0,85.7,13.3,16.2,81.9,5.93,7.74,76.6,0.90,2.37,38.1,0.11,1.75,1.75,0.45,0.11,3.22,31.0,28.1,2.88,0.96,0.17,0.00,2.54,0.23,1.47,0.68,0.62,0.06,23.2,0.00,0.85,3.62,2.37,0.56,0.23,0.11,0.28,0.06,0.28,0.17,0.0,0.0,0.06,0.0,0.06,1.64,0.51,0.45,0.90,0.28,0.51,1.47,34.6,0.96,1.69,0.11,1.58,0.06,1.69,0.28,0.06,44.0,0.40,4.35,19.0,21.50,2.49,44.0,3.73,1.19,31.8,1.75,47.0,26.7,136.1,56.6,1.53,1.07,0.40,2.60,3.11,30.2,5.65,0.11,0.0,0.0,0.62,2.26,0.17,2.54,0.51,0.0,0.0,0.00,4.86,0.34,1.19,22.2,€15.00m,15000000.0
1,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,1987,22,22,1980,22.0,0,0.86,0.05,5.3,0.00,0.00,13.5,0.00,0.0,0.0,38.5,47.2,81.5,751.5,318.5,10.9,12.9,84.5,23.20,25.70,90.1,3.77,7.00,53.9,0.05,0.27,2.91,0.09,0.00,4.50,47.2,43.3,3.73,3.32,0.00,0.55,0.18,0.09,0.00,0.00,0.00,0.00,38.5,0.23,0.59,1.14,0.86,0.00,0.00,0.18,0.00,0.09,0.18,0.14,0.0,0.0,0.05,0.0,0.00,2.50,1.59,1.45,1.00,0.05,1.32,1.68,78.4,0.36,2.23,0.77,1.45,2.00,4.50,2.91,0.05,59.2,6.23,27.50,29.5,2.73,1.09,59.2,0.68,0.32,46.7,0.36,53.3,40.0,234.2,125.0,0.55,0.23,0.09,0.73,0.68,34.5,0.23,0.09,0.0,0.0,1.32,0.50,0.05,0.18,1.59,0.0,0.0,0.00,6.64,2.18,1.23,64.0,€400k,400000.0
2,3,Himad Abdelli,FRA,MFFW,Angers,Ligue 1,23,1999,14,8,770,8.6,0,1.05,0.35,33.3,0.00,0.00,19.2,0.00,0.0,0.0,40.0,49.5,80.8,676.0,188.1,18.5,22.0,84.1,15.50,18.70,82.6,4.42,5.93,74.5,0.00,1.51,3.95,1.74,0.35,6.40,49.5,48.1,1.16,0.35,0.12,0.23,1.05,0.81,0.00,0.00,0.00,0.00,40.0,0.23,1.16,2.67,2.44,0.00,0.00,0.12,0.00,0.12,0.00,0.00,0.0,0.0,0.00,0.0,0.00,2.91,1.40,1.28,1.40,0.23,1.63,2.67,60.9,1.05,1.51,0.12,1.40,0.93,3.84,0.93,0.00,62.6,0.93,11.40,36.0,17.40,1.16,62.6,3.84,2.09,54.5,1.51,39.4,48.5,298.5,151.0,2.56,2.56,0.47,2.09,1.05,43.4,5.93,0.12,0.0,0.0,1.74,1.28,0.00,1.05,1.40,0.0,0.0,0.00,8.14,0.93,1.05,47.1,€7.00m,7000000.0
3,4,Salis Abdul Samed,GHA,MF,Lens,Ligue 1,22,2000,20,20,1799,20.0,1,0.60,0.15,25.0,0.08,0.33,20.3,0.00,0.0,0.0,59.5,64.9,91.6,946.3,226.9,29.6,31.8,93.2,24.70,26.20,94.3,3.35,4.30,77.9,0.00,0.50,6.00,0.55,0.10,5.60,64.9,63.1,1.40,1.30,0.05,0.20,0.35,0.10,0.00,0.00,0.00,0.00,59.5,0.35,0.40,1.60,1.35,0.00,0.10,0.10,0.00,0.05,0.00,0.00,0.0,0.0,0.00,0.0,0.00,1.50,0.80,0.55,0.85,0.10,0.85,1.30,65.4,0.45,1.30,0.35,0.95,1.10,2.60,0.80,0.00,73.3,2.10,12.00,49.6,12.20,0.70,73.3,1.25,0.70,56.0,0.40,32.0,61.0,316.9,117.5,1.25,1.95,0.15,1.35,1.30,56.5,1.70,0.15,0.0,0.0,2.45,1.35,0.00,0.35,0.80,0.0,0.0,0.05,6.60,0.50,0.50,50.0,€5.00m,5000000.0
4,5,Laurent Abergel,FRA,MF,Lorient,Ligue 1,30,1993,15,15,1165,12.9,0,0.31,0.00,0.0,0.00,0.00,23.9,0.00,0.0,0.0,37.9,43.4,87.3,613.6,224.7,17.9,19.4,92.4,15.70,17.80,88.6,2.64,3.95,66.7,0.08,0.62,3.88,0.39,0.00,5.04,43.4,42.6,0.78,0.78,0.39,0.16,0.23,0.00,0.00,0.00,0.00,0.00,37.9,0.08,0.31,1.24,1.01,0.08,0.00,0.08,0.00,0.08,0.08,0.08,0.0,0.0,0.00,0.0,0.00,3.80,2.02,2.64,1.16,0.00,1.32,3.26,40.5,1.94,1.40,0.23,1.16,1.16,4.96,1.55,0.00,54.7,3.26,19.20,31.4,4.88,0.23,54.7,0.93,0.54,58.3,0.31,33.3,41.0,174.3,72.7,0.47,0.93,0.00,1.32,0.78,36.4,0.47,0.16,0.0,0.0,0.93,1.01,0.00,0.23,2.02,0.0,0.0,0.00,6.51,0.31,0.39,44.4,€2.50m,2500000.0

In [ ]:
import pandas as pd

# Load the scraped market value data
df_results_2 = pd.read_csv("player_market_values.csv")

# Preview columns
print("Columns in scraped data:", df_results_2.columns.tolist())

# Clean invalid entries
df_results_2 = df_results_2[
    (df_results_2['Market Value'].notna()) &
    (~df_results_2['Market Value'].isin(['Not Found', '-']))
]

# Conversion function (robust)
def convert_market_value(value):
    try:
        value = str(value).replace("€", "").replace(",", "").strip().lower()
        if "m" in value:
            return float(value.replace("m", "")) * 1_000_000
        elif "k" in value:
            return float(value.replace("k", "")) * 1_000
        else:
            return float(value)
    except:
        return None  # fallback if conversion fails

# Apply conversion and verify
df_results_2["Market Value Euros"] = df_results_2["Market Value"].apply(convert_market_value)

print("✅ Conversion done. Non-null count:", df_results_2["Market Value Euros"].notna().sum())

# Merge with player_raw
print("Before merge:", player_raw.shape)
player_raw = player_raw.merge(df_results_2, how="left", on="Player")
print("After merge:", player_raw.shape)

# Check if the column exists after merge
if "Market Value Euros" in player_raw.columns:
    player_raw = player_raw[~player_raw["Market Value Euros"].isna()]
    print("After filtering:", player_raw.shape)
else:
    print("⚠️ 'Market Value Euros' column missing after merge!")

# Save cleaned dataset
player_raw.to_csv("player_data_with_market_value.csv", index=False)
print("✅ Saved: player_data_with_market_value.csv")

Columns in scraped data: ['Player', 'Market Value']
✅ Conversion done. Non-null count: 2266
Before merge: (2415, 128)
After merge: (2415, 130)
After filtering: (2415, 130)
✅ Saved: player_data_with_market_value.csv

In [ ]:
import pandas as pd
player_data = pd.read_csv("player_data_with_reddit_sentiment.csv")
player_data.columns.tolist()

['Rk',
 'Player',
 'Nation',
 'Pos',
 'Squad',
 'Comp',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 '90s',
 'Goals',
 'Shots',
 'SoT',
 'SoT%',
 'G/Sh',
 'G/SoT',
 'ShoDist',
 'ShoFK',
 'ShoPK',
 'PKatt',
 'PasTotCmp',
 'PasTotAtt',
 'PasTotCmp%',
 'PasTotDist',
 'PasTotPrgDist',
 'PasShoCmp',
 'PasShoAtt',
 'PasShoCmp%',
 'PasMedCmp',
 'PasMedAtt',
 'PasMedCmp%',
 'PasLonCmp',
 'PasLonAtt',
 'PasLonCmp%',
 'Assists',
 'PasAss',
 'Pas3rd',
 'PPA',
 'CrsPA',
 'PasProg',
 'PasAtt',
 'PasLive',
 'PasDead',
 'PasFK',
 'TB',
 'Sw',
 'PasCrs',
 'TI',
 'CK',
 'CkIn',
 'CkOut',
 'CkStr',
 'PasCmp',
 'PasOff',
 'PasBlocks',
 'SCA',
 'ScaPassLive',
 'ScaPassDead',
 'ScaDrib',
 'ScaSh',
 'ScaFld',
 'ScaDef',
 'GCA',
 'GcaPassLive',
 'GcaPassDead',
 'GcaDrib',
 'GcaSh',
 'GcaFld',
 'GcaDef',
 'Tkl',
 'TklWon',
 'TklDef3rd',
 'TklMid3rd',
 'TklAtt3rd',
 'TklDri',
 'TklDriAtt',
 'TklDri%',
 'TklDriPast',
 'Blocks',
 'BlkSh',
 'BlkPass',
 'Int',
 'Tkl+Int',
 'Clr',
 'Err',
 'Touches',
 'TouDefPen',
 'TouDef3rd',
 'TouMid3rd',
 'TouAtt3rd',
 'TouAttPen',
 'TouLive',
 'ToAtt',
 'ToSuc',
 'ToSuc%',
 'ToTkl',
 'ToTkl%',
 'Carries',
 'CarTotDist',
 'CarPrgDist',
 'CarProg',
 'Car3rd',
 'CPA',
 'CarMis',
 'CarDis',
 'Rec',
 'RecProg',
 'CrdY',
 'CrdR',
 '2CrdY',
 'Fls',
 'Fld',
 'Off',
 'Crs',
 'TklW',
 'PKwon',
 'PKcon',
 'OG',
 'Recov',
 'AerWon',
 'AerLost',
 'AerWon%',
 'Market Value_x',
 'Market Value Euros_x',
 'Market Value_y',
 'Market Value Euros_y',
 'Market Value',
 'Market Value Euros',
 'negative',
 'neutral',
 'positive',
 'AvgSentimentScore']

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# Load your dataset
df_players = pd.read_csv("player_data_with_reddit_sentiment.csv")  # should contain 'Player' column

# Prepare list of unique players
player_list = df_players['Player'].unique()

# Base URL template for injury pages
# Note: Transfermarkt uses player-specific URLs like https://www.transfermarkt.com/{slug}/verletzungen/spieler/{id}
# Since we may not have the slug or id in your dataset, we first need to search the player to get it.
search_url_template = "https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={}"

# DataFrame to store results
injury_results = []

# Loop through players
for i, player in enumerate(player_list, start=1):
    print(f"Processing player {i}/{len(player_list)}: {player}")

    try:
        # 1️⃣ Search the player to get their profile URL
        search_url = search_url_template.format(player.replace(" ", "+"))
        response = requests.get(search_url, headers={"User-Agent": "Mozilla/5.0"})
        soup = BeautifulSoup(response.text, "html.parser")

        # Try to find the first search result
        link_tag = soup.select_one("a.spielprofil_tooltip")
        if link_tag:
            player_href = link_tag['href']
            player_slug_id = player_href.split("/spieler/")[-1]  # e.g., '406499'
            player_slug = player_href.split("/")[1]

            # 2️⃣ Build injury page URL
            injury_url = f"https://www.transfermarkt.com/{player_slug}/verletzungen/spieler/{player_slug_id}"
            injury_resp = requests.get(injury_url, headers={"User-Agent": "Mozilla/5.0"})
            injury_soup = BeautifulSoup(injury_resp.text, "html.parser")

            # 3️⃣ Find the injuries table
            table = injury_soup.find("table", class_="items")
            if table:
                rows = table.find_all("tr", class_=["odd", "even"])
                for r in rows:
                    cols = r.find_all("td")
                    if len(cols) >= 5:
                        injury_type = cols[1].text.strip()
                        start_date = cols[2].text.strip()
                        end_date = cols[3].text.strip()
                        days_out = cols[4].text.strip()

                        injury_results.append({
                            "Player": player,
                            "injury_type": injury_type,
                            "start_date": start_date,
                            "end_date": end_date,
                            "days_out": days_out
                        })
            else:
                # No injuries found
                injury_results.append({
                    "Player": player,
                    "injury_type": "None",
                    "start_date": "",
                    "end_date": "",
                    "days_out": 0
                })
        else:
            # Player not found
            injury_results.append({
                "Player": player,
                "injury_type": "Not Found",
                "start_date": "",
                "end_date": "",
                "days_out": 0
            })

    except Exception as e:
        injury_results.append({
            "Player": player,
            "injury_type": "Error",
            "start_date": "",
            "end_date": "",
            "days_out": str(e)
        })

    # Pause to avoid IP ban
    time.sleep(2)

# Convert results to DataFrame
df_injuries = pd.DataFrame(injury_results)

# Save to CSV
df_injuries.to_csv("player_injuries.csv", index=False)
print("✅ Injury scraping completed and saved to player_injuries.csv")

Processing player 1/2266: Brenden Aaronson
Processing player 2/2266: Yunis Abdelhamid
Processing player 3/2266: Himad Abdelli
Processing player 4/2266: Salis Abdul Samed
Processing player 5/2266: Laurent Abergel
Processing player 6/2266: Oliver Abildgaard
Processing player 7/2266: Matthis Abline
Processing player 8/2266: Abner
Processing player 9/2266: Zakaria Aboukhlal
Processing player 10/2266: Tammy Abraham
Processing player 11/2266: Francesco Acerbi
Processing player 12/2266: Mohamed Achi
Processing player 13/2266: Marcos Acuña
Processing player 14/2266: Che Adams
Processing player 15/2266: Tyler Adams
Processing player 16/2266: Sargis Adamyan
Processing player 17/2266: Tosin Adarabioyo
Processing player 18/2266: Martin Adeline
Processing player 19/2266: Karim Adeyemi
Processing player 20/2266: Amine Adli
Processing player 21/2266: Yacine Adli
Processing player 22/2266: Michel Aebischer
Processing player 23/2266: Felix Afena-Gyan
Processing player 24/2266: Emmanuel Agbadou
Processing player 25/2266: Lucien Agoume
Processing player 26/2266: Felix Agu
Processing player 27/2266: Álvaro Aguado
Processing player 28/2266: Kevin Agudelo
Processing player 29/2266: Nayef Aguerd
Processing player 30/2266: Ruben Aguilar
Processing player 31/2266: Naouirou Ahamada
Processing player 32/2266: Jean-Eudes Aholou
Processing player 33/2266: Joseph Aidoo
Processing player 34/2266: Ola Aina
Processing player 35/2266: Kristoffer Ajer
Processing player 36/2266: Ludovic Ajorque
Processing player 37/2266: Manuel Akanji
Processing player 38/2266: Nathan Aké
Processing player 39/2266: Sergio Akieme
Processing player 40/2266: Maghnes Akliouche
Processing player 41/2266: Paul Akouokou
Processing player 42/2266: Kevin Akpoguma
Processing player 43/2266: David Alaba
Processing player 44/2266: Tomás Alarcón
Processing player 45/2266: Lucas Alario
Processing player 46/2266: Jordi Alba
Processing player 47/2266: Luis Alberto
Processing player 48/2266: Raúl Albiol
Processing player 49/2266: Carlos Alcaraz
Processing player 50/2266: Rubén Alcaraz
Processing player 51/2266: Omar Alderete
Processing player 52/2266: Iván Alejo
Processing player 53/2266: Carles Aleñá
Processing player 54/2266: Trent Alexander-Arnold
Processing player 55/2266: Ángel Algobia
Processing player 56/2266: Mohamed Ali Cho
Processing player 57/2266: Faride Alidou
Processing player 58/2266: Alisson
Processing player 59/2266: Jim Allevinah
Processing player 60/2266: Dele Alli
Processing player 61/2266: Domingos André Ribeiro Almeida
Processing player 62/2266: Miguel Almirón
Processing player 63/2266: Marcos Alonso
Processing player 64/2266: Carlos Álvarez
Processing player 65/2266: Gastón Álvarez
Processing player 66/2266: Julián Álvarez
Processing player 67/2266: Agustín Álvarez Martínez
Processing player 68/2266: Yeray Álvarez
Processing player 69/2266: Ibrahim Amadou
Processing player 70/2266: Daniel Amartey
Processing player 71/2266: Amath
Processing player 72/2266: Jordan Amavi
Processing player 73/2266: Kelvin Amian
Processing player 74/2266: Bruno Amione
Processing player 75/2266: Nadiem Amiri
Processing player 76/2266: Ethan Ampadu
Processing player 77/2266: Sofyan Amrabat
Processing player 78/2266: Joachim Andersen
Processing player 79/2266: Elliot Anderson
Processing player 80/2266: Felipe Anderson
Processing player 81/2266: Benjamin André
Processing player 82/2266: Komnen Andri?
Processing player 83/2266: Robert Andrich
Processing player 84/2266: Angeliño
Processing player 85/2266: Fabrizio Angileri
Processing player 86/2266: Jaidon Anthony
Processing player 87/2266: Janis Antiste
Processing player 88/2266: Waldemar Anton
Processing player 89/2266: Michail Antonio
Processing player 90/2266: Antony
Processing player 91/2266: Valentin Antov
Processing player 92/2266: Christopher Antwi-Adjei
Processing player 93/2266: Anuar
Processing player 94/2266: Houssem Aouar
Processing player 95/2266: Adil Aouchiche
Processing player 96/2266: Dennis Appiah
Processing player 97/2266: Mauro Arambarri
Processing player 98/2266: Charles Aránguiz
Processing player 99/2266: Ronald Araújo
Processing player 100/2266: Cameron Archer
Processing player 101/2266: Taïryk Arconte
Processing player 102/2266: Alphonse Areola
Processing player 103/2266: Joe Aribo
Processing player 104/2266: Adam Armstrong
Processing player 105/2266: Stuart Armstrong
Processing player 106/2266: Marko Arnautovi?
Processing player 107/2266: Maximilian Arnold
Processing player 108/2266: Kepa Arrizabalaga
Processing player 109/2266: Roberto Arroyo
Processing player 110/2266: Tolgay Arslan
Processing player 111/2266: Arthur
Processing player 112/2266: Santiago Arzamendia
Processing player 113/2266: Takuma Asano
Processing player 114/2266: Santiago Ascacíbar
Processing player 115/2266: Marco Asensio
Processing player 116/2266: Kristoffer Askildsen
Processing player 117/2266: Fisnik Asllani
Processing player 118/2266: Kristjan Asllani
Processing player 119/2266: Iago Aspas
Processing player 120/2266: Lorenz Assignon
Processing player 121/2266: Youcef Atal
Processing player 122/2266: Pierre-Emerick Aubameyang
Processing player 123/2266: Emil Audero
Processing player 124/2266: Tommaso Augello
Processing player 125/2266: Ludwig Augustinsson
Processing player 126/2266: Serge Aurier
Processing player 127/2266: Ezequiel Ávila
Processing player 128/2266: Taiwo Awoniyi
Processing player 129/2266: André Ayew
Processing player 130/2266: Jordan Ayew
Processing player 131/2266: Kaan Ayhan
Processing player 132/2266: Luke Ayling
Processing player 133/2266: Ayman Azhil
Processing player 134/2266: Sardar Azmoun
Processing player 135/2266: César Azpilicueta
Processing player 136/2266: Sanoussy Ba
Processing player 137/2266: Iddrisu Baba
Processing player 138/2266: Sr?an Babi?
Processing player 139/2266: Loïc Bade
Processing player 140/2266: Édgar Badía
Processing player 141/2266: Benoît Badiashile
Processing player 142/2266: Alex Baena
Processing player 143/2266: Jaime Báez
Processing player 144/2266: Leon Bailey
Processing player 145/2266: Eric Bailly
Processing player 146/2266: Brandon Baiye
Processing player 147/2266: Stefan Bajcetic
Processing player 148/2266: Nedim Bajrami
Processing player 149/2266: Cédric Bakambu
Processing player 150/2266: Mitchel Bakker
Processing player 151/2266: Ridle Baku
Processing player 152/2266: Tommaso Baldanzi
Processing player 153/2266: Alejandro Balde
Processing player 154/2266: Thierno Balde
Processing player 155/2266: Carlos Baleba
Processing player 156/2266: Leonardo Balerdi
Processing player 157/2266: Iván Balliu
Processing player 158/2266: Fodé Ballo-Touré
Processing player 159/2266: Folarin Balogun
Processing player 160/2266: Abdoulaye Bamba
Processing player 161/2266: Jonathan Bamba
Processing player 162/2266: Patrick Bamford
Processing player 163/2266: Lameck Banda
Processing player 164/2266: Filippo Bandinelli
Processing player 165/2266: Léo Baptistão
Processing player 166/2266: Shandon Baptiste
Processing player 167/2266: Antonín Barák
Processing player 168/2266: Andrea Barberis
Processing player 169/2266: Bradley Barcola
Processing player 170/2266: Melvin Bard
Processing player 171/2266: Keidi Bare
Processing player 172/2266: Nicolò Barella
Processing player 173/2266: Kike Barja
Processing player 174/2266: Ross Barkley
Processing player 175/2266: Aymen Barkok
Processing player 176/2266: Harvey Barnes
Processing player 177/2266: Leandro Barreiro Martins
Processing player 178/2266: Ander Barrenetxea
Processing player 179/2266: Pablo Barrios
Processing player 180/2266: Musa Barrow
Processing player 181/2266: Federico Baschirotto
Processing player 182/2266: Gil Bastião Dias
Processing player 183/2266: Alessandro Bastoni
Processing player 184/2266: Simone Bastoni
Processing player 185/2266: Rodrigo Battaglia
Processing player 186/2266: Maximilian Bauer
Processing player 187/2266: Oliver Baumann
Processing player 188/2266: Timo Baumgartl
Processing player 189/2266: Christoph Baumgartner
Processing player 190/2266: Cyrille Bayala
Processing player 191/2266: Brian Bayeye
Processing player 192/2266: Noah Joel Sarenren Bazee
Processing player 193/2266: Gavin Bazunu
Processing player 194/2266: Ihlas Bebou
Processing player 195/2266: Rodrigo Becão
Processing player 196/2266: Mads Bech Sørensen
Processing player 197/2266: Julius Beck
Processing player 198/2266: Sheraldo Becker
Processing player 199/2266: Jan Bednarek
Processing player 200/2266: Donny van de Beek
Processing player 201/2266: Asmir Begovi?
Processing player 202/2266: Yanis Begraoui
Processing player 203/2266: Kevin Behrens
Processing player 204/2266: Alexis Beka Beka
Processing player 205/2266: Jérémie Bela
Processing player 206/2266: Youcef Belaïli
Processing player 207/2266: Haris Belkebla
Processing player 208/2266: Stefan Bell
Processing player 209/2266: Armel Bella Kotchap
Processing player 210/2266: Raoul Bellanova
Processing player 211/2266: Jean-Ricner Bellegarde
Processing player 212/2266: Héctor Bellerín
Processing player 213/2266: Jude Bellingham
Processing player 214/2266: Andrea Belotti
Processing player 215/2266: Fran Beltrán
Processing player 216/2266: Eliesse Ben Seghir
Processing player 217/2266: Salim Ben Seghir
Processing player 218/2266: Wissam Ben Yedder
Processing player 219/2266: Ismaël Bennacer
Processing player 220/2266: Saïd Benrahma
Processing player 221/2266: Ramy Bensebaini
Processing player 222/2266: Nabil Bentaleb
Processing player 223/2266: Rodrigo Bentancur
Processing player 224/2266: Karim Benzema
Processing player 225/2266: Domenico Berardi
Processing player 226/2266: Yuri Berchiche
Processing player 227/2266: Álex Berenguer
Processing player 228/2266: Bartosz Bereszy?ski
Processing player 229/2266: Patrick Berg
Processing player 230/2266: Mitchell van Bergen
Processing player 231/2266: Mergim Berisha
Processing player 232/2266: Quentin Bernard
Processing player 233/2266: Paul Bernardoni
Processing player 234/2266: Juan Bernat
Processing player 235/2266: Matteo Bianchetti
Processing player 236/2266: Alessandro Bianco
Processing player 237/2266: Giulian Biancone
Processing player 238/2266: Ermin Bi?ak?i?
Processing player 239/2266: Pedro Bigas
Processing player 240/2266: Jaka Bijol
Processing player 241/2266: El Bilal Touré
Processing player 242/2266: Philip Billing
Processing player 243/2266: Jean-Claude Billong
Processing player 244/2266: Cristiano Biraghi
Processing player 245/2266: Samuele Birindelli
Processing player 246/2266: Veljko Birman?evi?
Processing player 247/2266: Tom Bischof
Processing player 248/2266: Yves Bissouma
Processing player 249/2266: Kristijan Bistrovi?
Processing player 250/2266: Leonardo Bittencourt
Processing player 251/2266: Marco Bizot
Processing player 252/2266: Lautaro Blanco
Processing player 253/2266: Rubén Blanco
Processing player 254/2266: Ludovic Blas
Processing player 255/2266: Janis Blaswich
Processing player 256/2266: Miha Bla?i?
Processing player 257/2266: Joaquín Blázquez
Processing player 258/2266: Alexis Blin
Processing player 259/2266: Daley Blind
Processing player 260/2266: Myron Boadu
Processing player 261/2266: Antonin Bobichon
Processing player 262/2266: Jean-Paul Boëtius
Processing player 263/2266: Jeremie Boga
Processing player 264/2266: Emil Bohinen
Processing player 265/2266: Quentin Boisgard
Processing player 266/2266: Willy Boly
Processing player 267/2266: Giacomo Bonaventura
Processing player 268/2266: Federico Bonazzoli
Processing player 269/2266: Warren Bondo
Processing player 270/2266: Theo Bongonda
Processing player 271/2266: Kevin Bonifazi
Processing player 272/2266: Neto Borges
Processing player 273/2266: Yvandro Borges Sanches
Processing player 274/2266: Sebastiaan Bornauw
Processing player 275/2266: Rafael Borré
Processing player 276/2266: Erik Botheim
Processing player 277/2266: Sven Botman
Processing player 278/2266: Kenji-Van Boto
Processing player 279/2266: Badredine Bouanani
Processing player 280/2266: Hicham Boudaoui
Processing player 281/2266: Franci Bouebari
Processing player 282/2266: Sofiane Boufal
Processing player 283/2266: Yassine Bounou
Processing player 284/2266: Mehdi Bourabia
Processing player 285/2266: Benjamin Bourigeaud
Processing player 286/2266: Edoardo Bove
Processing player 287/2266: Jarrod Bowen
Processing player 288/2266: Lucas Boyé
Processing player 289/2266: Jayden Braaf
Processing player 290/2266: Domagoj Bradari?
Processing player 291/2266: Bilal Brahimi
Processing player 292/2266: Martin Braithwaite
Processing player 293/2266: Juan Brandáriz
Processing player 294/2266: Julian Brandt
Processing player 295/2266: Lilian Brassier
Processing player 296/2266: Fabian Bredlow
Processing player 297/2266: James Bree
Processing player 298/2266: Josip Brekalo
Processing player 299/2266: Gleison Bremer
Processing player 300/2266: Armando Broja
Processing player 301/2266: Dylan Bronn
Processing player 302/2266: John Brooks
Processing player 303/2266: Moritz Broschinski
Processing player 304/2266: Marcelo Brozovi?
Processing player 305/2266: Lewis Brunt
Processing player 306/2266: Jacob Bruun Larsen
Processing player 307/2266: Andreas Bruus
Processing player 308/2266: Bryan
Processing player 309/2266: Joe Bryan
Processing player 310/2266: Lee Buchanan
Processing player 311/2266: Ante Budimir
Processing player 312/2266: Emi Buendía
Processing player 313/2266: Hugo Bueno
Processing player 314/2266: Santiago Bueno
Processing player 315/2266: Adam Buksa
Processing player 316/2266: Marius Bülter
Processing player 317/2266: Cristian Buonaiuto
Processing player 318/2266: Facundo Buonanotte
Processing player 319/2266: Alessandro Buongiorno
Processing player 320/2266: Delano Burgzorg
Processing player 321/2266: Jonathan Burkardt
Processing player 322/2266: Oliver Burke
Processing player 323/2266: Dan Burn
Processing player 324/2266: Maxime Busi
Processing player 325/2266: Sergio Busquets
Processing player 326/2266: Aurélio Buta
Processing player 327/2266: Marcin Bu?ka
Processing player 328/2266: Jamie Bynoe-Gittens
Processing player 329/2266: Juan Cabal
Processing player 330/2266: Rémy Cabella
Processing player 331/2266: Leandro Cabrera
Processing player 332/2266: Liberato Cacace
Processing player 333/2266: Anthony Caci
Processing player 334/2266: Moisés Caicedo
Processing player 335/2266: Tom Cairney
Processing player 336/2266: Jens Cajuste
Processing player 337/2266: Davide Calabria
Processing player 338/2266: Mattia Caldara
Processing player 339/2266: Luca Caldirola
Processing player 340/2266: Fernando Calero
Processing player 341/2266: Duje ?aleta-Car
Processing player 342/2266: Kerim Calhanoglu
Processing player 343/2266: Alexander Callens
Processing player 344/2266: Dominic Calvert-Lewin
Processing player 345/2266: Mahdi Camara
Processing player 346/2266: Mohamed Camara
Processing player 347/2266: Ousmane Camara
Processing player 348/2266: Eduardo Camavinga
Processing player 349/2266: Nicolò Cambiaghi
Processing player 350/2266: Andrea Cambiaso
Processing player 351/2266: Axel Camblan
Processing player 352/2266: Sergio Camello
Processing player 353/2266: Chem Campbell
Processing player 354/2266: Emre Can
Processing player 355/2266: Sergio Canales
Processing player 356/2266: Matteo Cancellieri
Processing player 357/2266: João Cancelo
Processing player 358/2266: Thomas Cannon
Processing player 359/2266: Sergi Canós
Processing player 360/2266: Pierrick Capelle
Processing player 361/2266: Gianluca Caprari
Processing player 362/2266: Maxence Caqueret
Processing player 363/2266: Andrea Carboni
Processing player 364/2266: Valentin Carboni
Processing player 365/2266: Isaac Carcelen
Processing player 366/2266: Irvin Cardona
Processing player 367/2266: Diego Carlos
Processing player 368/2266: José Carlos Lazo
Processing player 369/2266: Carmona
Processing player 370/2266: Marco Carnesecchi
Processing player 371/2266: Yannick Carrasco
Processing player 372/2266: Fabio Carvalho
Processing player 373/2266: Matis Carvalho
Processing player 374/2266: William Carvalho
Processing player 375/2266: Nicolò Casale
Processing player 376/2266: Casemiro
Processing player 377/2266: Matty Cash
Processing player 378/2266: Timothy Castagne
Processing player 379/2266: Michele Castagnetti
Processing player 380/2266: Koen Casteels
Processing player 381/2266: Valentín Castellanos
Processing player 382/2266: Jean-Charles Castelletto
Processing player 383/2266: Samu Castillejo
Processing player 384/2266: Jonny Castro
Processing player 385/2266: Gaetano Castrovilli
Processing player 386/2266: Danilo Cataldi
Processing player 387/2266: Catena
Processing player 388/2266: Yoann Cathline
Processing player 389/2266: Maximiliano Caufriez
Processing player 390/2266: Edinson Cavani
Processing player 391/2266: Dani Ceballos
Processing player 392/2266: Federico Ceccherini
Processing player 393/2266: Assan Ceesay
Processing player 394/2266: Emil Ceide
Processing player 395/2266: Zeki Çelik
Processing player 396/2266: Fabien Centonze
Processing player 397/2266: Franco Cervi
Processing player 398/2266: Julio César Enciso
Processing player 399/2266: Leonardo César Jardim
Processing player 400/2266: Julian Chabot
Processing player 401/2266: El Chadaille Bitshiabu
Processing player 402/2266: Fares Chaïbi
Processing player 403/2266: Nathaniel Chalobah
Processing player 404/2266: Trevoh Chalobah
Processing player 405/2266: Calum Chambers
Processing player 406/2266: Timothy Chandler
Processing player 407/2266: Brendan Chardonnet
Processing player 408/2266: Xavier Chavalerin
Processing player 409/2266: Pep Chavarría
Processing player 410/2266: Rayan Cherki
Processing player 411/2266: Lucas Chevalier
Processing player 412/2266: Fabio Chiarodia
Processing player 413/2266: Federico Chiesa
Processing player 414/2266: Ben Chilwell
Processing player 415/2266: Vlad Chiriche?
Processing player 416/2266: Pedro Chirivella
Processing player 417/2266: Joris Chotard
Processing player 418/2266: Andreas Christensen
Processing player 419/2266: Oliver Christensen
Processing player 420/2266: Ryan Christie
Processing player 421/2266: Carney Chukwuemeka
Processing player 422/2266: Samuel Chukwueze
Processing player 423/2266: Darko Churlinov
Processing player 424/2266: Víctor Chust
Processing player 425/2266: Yanis Cimignani
Processing player 426/2266: Tio Cipot
Processing player 427/2266: Pathé Ciss
Processing player 428/2266: Souleymane Cissé
Processing player 429/2266: Patrick Ciurria
Processing player 430/2266: Bobby Clark
Processing player 431/2266: Alexis Claude-Maurice
Processing player 432/2266: Jonathan Clauss
Processing player 433/2266: Carlos Clerc
Processing player 434/2266: Nathaniel Clyne
Processing player 435/2266: Conor Coady
Processing player 436/2266: Marcus Coco
Processing player 437/2266: Alexandre Coeff
Processing player 438/2266: Jack Colback
Processing player 439/2266: Séamus Coleman
Processing player 440/2266: David ?olina
Processing player 441/2266: Álex Collado
Processing player 442/2266: Diego Collado
Processing player 443/2266: Omar Colley
Processing player 444/2266: Nathan Collins
Processing player 445/2266: Lorenzo Colombo
Processing player 446/2266: Andrea Colpani
Processing player 447/2266: Levi Colwill
Processing player 448/2266: Kingsley Coman
Processing player 449/2266: Eray Cömert
Processing player 450/2266: Santi Comesaña
Processing player 451/2266: Andrea Consigli
Processing player 452/2266: Abdu Conté
Processing player 453/2266: Lewis Cook
Processing player 454/2266: Steve Cook
Processing player 455/2266: Liam Cooper
Processing player 456/2266: Copete
Processing player 457/2266: Diego Coppola
Processing player 458/2266: Francis Coquelin
Processing player 459/2266: Maxwel Cornet
Processing player 460/2266: Jesús Corona
Processing player 461/2266: Ángel Correa
Processing player 462/2266: Joaquín Correa
Processing player 463/2266: Thierry Correia
Processing player 464/2266: Alessandro Cortinovis
Processing player 465/2266: Danny da Costa
Processing player 466/2266: David Pereira da Costa
Processing player 467/2266: Diego Costa

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random

# Load your player list (from your main dataset)
df = pd.read_csv("2022-2023 Football Player Stats.csv", delimiter=';', encoding='latin1')  # Replace with your actual dataset
player_list = df['Player'].dropna().unique()

base_search_url = "https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query="
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
}

injury_results = []

for i, player in enumerate(player_list, start=1):
    print(f"🔍 [{i}/{len(player_list)}] Searching for: {player}")
    try:
        # Step 1️⃣: Find player profile
        search_url = base_search_url + player.replace(" ", "+")
        response = requests.get(search_url, headers=headers, timeout=10)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        # Find valid player profile
        link_tag = None
        for a in soup.find_all("a", href=True):
            if "/profil/spieler/" in a["href"]:
                link_tag = a
                break

        if not link_tag:
            print(f"⚠️ No Transfermarkt profile found for {player}")
            injury_results.append({
                "Player": player,
                "Injury": "Not Found",
                "From": "",
                "Until": "",
                "Days": ""
            })
            continue

        href = link_tag["href"]
        slug = href.split("/")[1]
        player_id = href.split("/spieler/")[-1]

        # Step 2️⃣: Go to injury page
        injury_url = f"https://www.transfermarkt.com/{slug}/verletzungen/spieler/{player_id}"
        injury_resp = requests.get(injury_url, headers=headers, timeout=10)
        injury_soup = BeautifulSoup(injury_resp.text, "html.parser")

        # Step 3️⃣: Locate injury table
        table = injury_soup.find("table", class_="items")

        if not table:
            print(f"ℹ️ No injury data for {player}")
            injury_results.append({
                "Player": player,
                "Injury": "None",
                "From": "",
                "Until": "",
                "Days": ""
            })
            continue

        # Step 4️⃣: Parse injury table
        rows = table.find_all("tr", class_=["odd", "even"])
        if not rows:
            injury_results.append({
                "Player": player,
                "Injury": "None",
                "From": "",
                "Until": "",
                "Days": ""
            })
            continue

        for row in rows:
            cols = [td.text.strip() for td in row.find_all("td")]
            if len(cols) >= 5:
                injury_results.append({
                    "Player": player,
                    "Injury": cols[1],
                    "From": cols[2],
                    "Until": cols[3],
                    "Days": cols[4]
                })

        # Random delay (2–5 seconds)
        time.sleep(random.uniform(2, 5))

    except Exception as e:
        print(f"❗ Error scraping {player}: {e}")
        injury_results.append({
            "Player": player,
            "Injury": "Error",
            "From": "",
            "Until": "",
            "Days": str(e)
        })

# Step 5️⃣: Save all results
df_injuries = pd.DataFrame(injury_results)
df_injuries.to_csv("player_injuries_all.csv", index=False)
print("\n✅ Scraping completed successfully! File saved as player_injuries_all.csv")

🔍 [1/2530] Searching for: Brenden Aaronson
🔍 [2/2530] Searching for: Yunis Abdelhamid
🔍 [3/2530] Searching for: Himad Abdelli
🔍 [4/2530] Searching for: Salis Abdul Samed
🔍 [5/2530] Searching for: Laurent Abergel
🔍 [6/2530] Searching for: Oliver Abildgaard
🔍 [7/2530] Searching for: Matthis Abline
ℹ️ No injury data for Matthis Abline
🔍 [8/2530] Searching for: Abner
🔍 [9/2530] Searching for: Zakaria Aboukhlal
🔍 [10/2530] Searching for: Tammy Abraham
🔍 [11/2530] Searching for: Francesco Acerbi
🔍 [12/2530] Searching for: Mohamed Achi
ℹ️ No injury data for Mohamed Achi
🔍 [13/2530] Searching for: Marcos Acuña
🔍 [14/2530] Searching for: Che Adams
🔍 [15/2530] Searching for: Tyler Adams
🔍 [16/2530] Searching for: Sargis Adamyan
🔍 [17/2530] Searching for: Tosin Adarabioyo
🔍 [18/2530] Searching for: Martin Adeline
🔍 [19/2530] Searching for: Karim Adeyemi
🔍 [20/2530] Searching for: Amine Adli
🔍 [21/2530] Searching for: Yacine Adli
🔍 [22/2530] Searching for: Michel Aebischer
🔍 [23/2530] Searching for: Felix Afena-Gyan
🔍 [24/2530] Searching for: Emmanuel Agbadou
🔍 [25/2530] Searching for: Lucien Agoume
🔍 [26/2530] Searching for: Felix Agu
🔍 [27/2530] Searching for: Álvaro Aguado
🔍 [28/2530] Searching for: Kevin Agudelo
🔍 [29/2530] Searching for: Nayef Aguerd
🔍 [30/2530] Searching for: Ruben Aguilar
🔍 [31/2530] Searching for: Naouirou Ahamada
🔍 [32/2530] Searching for: Amar Ahmed
ℹ️ No injury data for Amar Ahmed
🔍 [33/2530] Searching for: Jean-Eudes Aholou
🔍 [34/2530] Searching for: Joseph Aidoo
🔍 [35/2530] Searching for: Ola Aina
🔍 [36/2530] Searching for: Rayan Aït Nouri
⚠️ No Transfermarkt profile found for Rayan Aït Nouri
🔍 [37/2530] Searching for: Emanuel Aiwum
⚠️ No Transfermarkt profile found for Emanuel Aiwum
🔍 [38/2530] Searching for: Kristoffer Ajer
🔍 [39/2530] Searching for: Ludovic Ajorque
🔍 [40/2530] Searching for: Manuel Akanji
🔍 [41/2530] Searching for: Nathan Aké
🔍 [42/2530] Searching for: Sergio Akieme
🔍 [43/2530] Searching for: Maghnes Akliouche
🔍 [44/2530] Searching for: Paul Akouokou
🔍 [45/2530] Searching for: Jean-Daniel Akpa-Akpro
⚠️ No Transfermarkt profile found for Jean-Daniel Akpa-Akpro
🔍 [46/2530] Searching for: Kevin Akpoguma
🔍 [47/2530] Searching for: David Alaba
🔍 [48/2530] Searching for: Tomás Alarcón
🔍 [49/2530] Searching for: Lucas Alario
🔍 [50/2530] Searching for: Jordi Alba
🔍 [51/2530] Searching for: Luis Alberto
🔍 [52/2530] Searching for: Raúl Albiol
🔍 [53/2530] Searching for: Marc Albrighton
🔍 [54/2530] Searching for: Thiago Alcántara
🔍 [55/2530] Searching for: Carlos Alcaraz
🔍 [56/2530] Searching for: Rubén Alcaraz
🔍 [57/2530] Searching for: Omar Alderete
🔍 [58/2530] Searching for: Iván Alejo
🔍 [59/2530] Searching for: Doðan Alemdar
⚠️ No Transfermarkt profile found for Doðan Alemdar
🔍 [60/2530] Searching for: Carles Aleñá
🔍 [61/2530] Searching for: Trent Alexander-Arnold
🔍 [62/2530] Searching for: Alejandro Alfaro
🔍 [63/2530] Searching for: Ángel Algobia
🔍 [64/2530] Searching for: Mohamed Ali Cho
🔍 [65/2530] Searching for: Faride Alidou
🔍 [66/2530] Searching for: Alisson
🔍 [67/2530] Searching for: Jim Allevinah
🔍 [68/2530] Searching for: Dele Alli
🔍 [69/2530] Searching for: Domingos André Ribeiro Almeida
🔍 [70/2530] Searching for: Miguel Almirón
🔍 [71/2530] Searching for: Marcos Alonso
🔍 [72/2530] Searching for: Mickaël Alphonse
🔍 [73/2530] Searching for: Éder Álvarez Balanta
⚠️ No Transfermarkt profile found for Éder Álvarez Balanta
🔍 [74/2530] Searching for: Carlos Álvarez
🔍 [75/2530] Searching for: Gastón Álvarez
🔍 [76/2530] Searching for: Julián Álvarez
🔍 [77/2530] Searching for: Agustín Álvarez Martínez
🔍 [78/2530] Searching for: Yeray Álvarez
🔍 [79/2530] Searching for: Ibrahim Amadou
🔍 [80/2530] Searching for: Daniel Amartey
🔍 [81/2530] Searching for: Amath
🔍 [82/2530] Searching for: Jordan Amavi
🔍 [83/2530] Searching for: Kelvin Amian
🔍 [84/2530] Searching for: Bruno Amione
🔍 [85/2530] Searching for: Nadiem Amiri
🔍 [86/2530] Searching for: Ethan Ampadu
🔍 [87/2530] Searching for: Sofyan Amrabat
🔍 [88/2530] Searching for: Joachim Andersen
🔍 [89/2530] Searching for: Elliot Anderson
🔍 [90/2530] Searching for: Felipe Anderson
🔍 [91/2530] Searching for: Benjamin André
🔍 [92/2530] Searching for: Komnen Andri?
🔍 [93/2530] Searching for: Robert Andrich
🔍 [94/2530] Searching for: Angeliño
🔍 [95/2530] Searching for: Fabrizio Angileri
🔍 [96/2530] Searching for: Jaidon Anthony
ℹ️ No injury data for Jaidon Anthony
🔍 [97/2530] Searching for: Janis Antiste
🔍 [98/2530] Searching for: Waldemar Anton
🔍 [99/2530] Searching for: Marcos Antônio
🔍 [100/2530] Searching for: Michail Antonio
🔍 [101/2530] Searching for: Antony
🔍 [102/2530] Searching for: Valentin Antov
🔍 [103/2530] Searching for: Christopher Antwi-Adjei
🔍 [104/2530] Searching for: Anuar
🔍 [105/2530] Searching for: Houssem Aouar
🔍 [106/2530] Searching for: Adil Aouchiche
🔍 [107/2530] Searching for: Dennis Appiah
🔍 [108/2530] Searching for: Mauro Arambarri
🔍 [109/2530] Searching for: Charles Aránguiz
🔍 [110/2530] Searching for: Ronald Araújo
🔍 [111/2530] Searching for: Cameron Archer
🔍 [112/2530] Searching for: Taïryk Arconte
🔍 [113/2530] Searching for: Alphonse Areola
🔍 [114/2530] Searching for: Joe Aribo
🔍 [115/2530] Searching for: Adam Armstrong
🔍 [116/2530] Searching for: Stuart Armstrong
🔍 [117/2530] Searching for: Marko Arnautovi?
🔍 [118/2530] Searching for: Maximilian Arnold
🔍 [119/2530] Searching for: Kepa Arrizabalaga
🔍 [120/2530] Searching for: Roberto Arroyo
ℹ️ No injury data for Roberto Arroyo
🔍 [121/2530] Searching for: Tolgay Arslan
🔍 [122/2530] Searching for: Arthur
🔍 [123/2530] Searching for: Santiago Arzamendia
🔍 [124/2530] Searching for: Takuma Asano
🔍 [125/2530] Searching for: Santiago Ascacíbar
🔍 [126/2530] Searching for: Sergio Asenjo
🔍 [127/2530] Searching for: Marco Asensio
🔍 [128/2530] Searching for: Kristoffer Askildsen
🔍 [129/2530] Searching for: Fisnik Asllani
🔍 [130/2530] Searching for: Kristjan Asllani
🔍 [131/2530] Searching for: Iago Aspas
🔍 [132/2530] Searching for: Lorenz Assignon
❗ Error scraping Lorenz Assignon: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Lorenz+Assignon
🔍 [133/2530] Searching for: Youcef Atal
❗ Error scraping Youcef Atal: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Youcef+Atal
🔍 [134/2530] Searching for: Pierre-Emerick Aubameyang
❗ Error scraping Pierre-Emerick Aubameyang: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Pierre-Emerick+Aubameyang
🔍 [135/2530] Searching for: Emil Audero
❗ Error scraping Emil Audero: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Emil+Audero
🔍 [136/2530] Searching for: Tommaso Augello
❗ Error scraping Tommaso Augello: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Tommaso+Augello
🔍 [137/2530] Searching for: Ludwig Augustinsson
❗ Error scraping Ludwig Augustinsson: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Ludwig+Augustinsson
🔍 [138/2530] Searching for: Serge Aurier
❗ Error scraping Serge Aurier: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Serge+Aurier
🔍 [139/2530] Searching for: Mathias Autret
❗ Error scraping Mathias Autret: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Mathias+Autret
🔍 [140/2530] Searching for: Ezequiel Ávila
❗ Error scraping Ezequiel Ávila: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Ezequiel+%C3%81vila
🔍 [141/2530] Searching for: Cédric Avinel
❗ Error scraping Cédric Avinel: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=C%C3%A9dric+Avinel
🔍 [142/2530] Searching for: Taiwo Awoniyi
❗ Error scraping Taiwo Awoniyi: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Taiwo+Awoniyi
🔍 [143/2530] Searching for: Mehmet-Can Aydin
❗ Error scraping Mehmet-Can Aydin: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Mehmet-Can+Aydin
🔍 [144/2530] Searching for: André Ayew
❗ Error scraping André Ayew: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Andr%C3%A9+Ayew
🔍 [145/2530] Searching for: Jordan Ayew
❗ Error scraping Jordan Ayew: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Jordan+Ayew
🔍 [146/2530] Searching for: Kaan Ayhan
❗ Error scraping Kaan Ayhan: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Kaan+Ayhan
🔍 [147/2530] Searching for: Luke Ayling
❗ Error scraping Luke Ayling: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Luke+Ayling
🔍 [148/2530] Searching for: Ayman Azhil
❗ Error scraping Ayman Azhil: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Ayman+Azhil
🔍 [149/2530] Searching for: Sardar Azmoun
❗ Error scraping Sardar Azmoun: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Sardar+Azmoun
🔍 [150/2530] Searching for: César Azpilicueta
❗ Error scraping César Azpilicueta: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=C%C3%A9sar+Azpilicueta
🔍 [151/2530] Searching for: Sanoussy Ba
❗ Error scraping Sanoussy Ba: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Sanoussy+Ba
🔍 [152/2530] Searching for: Iddrisu Baba
❗ Error scraping Iddrisu Baba: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Iddrisu+Baba
🔍 [153/2530] Searching for: Sr?an Babi?
❗ Error scraping Sr?an Babi?: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Sr?an+Babi?
🔍 [154/2530] Searching for: Loïc Bade
❗ Error scraping Loïc Bade: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Lo%C3%AFc+Bade
🔍 [155/2530] Searching for: Édgar Badía
❗ Error scraping Édgar Badía: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=%C3%89dgar+Bad%C3%ADa
🔍 [156/2530] Searching for: Benoît Badiashile
❗ Error scraping Benoît Badiashile: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Beno%C3%AEt+Badiashile
🔍 [157/2530] Searching for: Alex Baena
❗ Error scraping Alex Baena: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Alex+Baena
🔍 [158/2530] Searching for: Jaime Báez
❗ Error scraping Jaime Báez: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Jaime+B%C3%A1ez
🔍 [159/2530] Searching for: Leon Bailey
❗ Error scraping Leon Bailey: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Leon+Bailey
🔍 [160/2530] Searching for: Eric Bailly
❗ Error scraping Eric Bailly: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Eric+Bailly
🔍 [161/2530] Searching for: Dénys Bain
❗ Error scraping Dénys Bain: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=D%C3%A9nys+Bain
🔍 [162/2530] Searching for: Brandon Baiye
❗ Error scraping Brandon Baiye: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Brandon+Baiye
🔍 [163/2530] Searching for: Stefan Bajcetic
❗ Error scraping Stefan Bajcetic: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Stefan+Bajcetic
🔍 [164/2530] Searching for: Nedim Bajrami
❗ Error scraping Nedim Bajrami: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Nedim+Bajrami
🔍 [165/2530] Searching for: Cédric Bakambu
❗ Error scraping Cédric Bakambu: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=C%C3%A9dric+Bakambu
🔍 [166/2530] Searching for: Mitchel Bakker
❗ Error scraping Mitchel Bakker: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Mitchel+Bakker
🔍 [167/2530] Searching for: Ridle Baku
❗ Error scraping Ridle Baku: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Ridle+Baku
🔍 [168/2530] Searching for: Tommaso Baldanzi
❗ Error scraping Tommaso Baldanzi: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Tommaso+Baldanzi
🔍 [169/2530] Searching for: Alejandro Balde
❗ Error scraping Alejandro Balde: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Alejandro+Balde
🔍 [170/2530] Searching for: Thierno Balde
❗ Error scraping Thierno Balde: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Thierno+Balde
🔍 [171/2530] Searching for: Carlos Baleba
❗ Error scraping Carlos Baleba: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Carlos+Baleba
🔍 [172/2530] Searching for: Mikel Balenziaga
❗ Error scraping Mikel Balenziaga: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Mikel+Balenziaga
🔍 [173/2530] Searching for: Leonardo Balerdi
❗ Error scraping Leonardo Balerdi: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Leonardo+Balerdi
🔍 [174/2530] Searching for: Iván Balliu
🔍 [175/2530] Searching for: Fodé Ballo-Touré
❗ Error scraping Fodé Ballo-Touré: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=Fod%C3%A9+Ballo-Tour%C3%A9
🔍 [176/2530] Searching for: Folarin Balogun
🔍 [177/2530] Searching for: Abdoulaye Bamba
ℹ️ No injury data for Abdoulaye Bamba
🔍 [178/2530] Searching for: Jonathan Bamba
🔍 [179/2530] Searching for: Patrick Bamford
🔍 [180/2530] Searching for: Lameck Banda
🔍 [181/2530] Searching for: Filippo Bandinelli
🔍 [182/2530] Searching for: Léo Baptistão
🔍 [183/2530] Searching for: Shandon Baptiste
🔍 [184/2530] Searching for: Antonín Barák
🔍 [185/2530] Searching for: Andrea Barberis
🔍 [186/2530] Searching for: Bradley Barcola
🔍 [187/2530] Searching for: Melvin Bard
🔍 [188/2530] Searching for: Keidi Bare
🔍 [189/2530] Searching for: Nicolò Barella
🔍 [190/2530] Searching for: Kike Barja
🔍 [191/2530] Searching for: Ross Barkley
🔍 [192/2530] Searching for: Aymen Barkok
🔍 [193/2530] Searching for: Harvey Barnes
🔍 [194/2530] Searching for: Leandro Barreiro Martins
🔍 [195/2530] Searching for: Ander Barrenetxea
🔍 [196/2530] Searching for: Mickaël Barreto
⚠️ No Transfermarkt profile found for Mickaël Barreto
🔍 [197/2530] Searching for: Pablo Barrios
🔍 [198/2530] Searching for: Musa Barrow
🔍 [199/2530] Searching for: Federico Baschirotto
🔍 [200/2530] Searching for: Toma Bai?
⚠️ No Transfermarkt profile found for Toma Bai?
🔍 [201/2530] Searching for: Gil Bastião Dias
🔍 [202/2530] Searching for: Alessandro Bastoni
🔍 [203/2530] Searching for: Simone Bastoni
🔍 [204/2530] Searching for: Rodrigo Battaglia
🔍 [205/2530] Searching for: Maximilian Bauer
🔍 [206/2530] Searching for: Oliver Baumann
🔍 [207/2530] Searching for: Timo Baumgartl
🔍 [208/2530] Searching for: Julian Baumgartlinger
🔍 [209/2530] Searching for: Christoph Baumgartner
🔍 [210/2530] Searching for: Cyrille Bayala
🔍 [211/2530] Searching for: Brian Bayeye
🔍 [212/2530] Searching for: Noah Joel Sarenren Bazee
🔍 [213/2530] Searching for: Gavin Bazunu
🔍 [214/2530] Searching for: Bebé
ℹ️ No injury data for Bebé
🔍 [215/2530] Searching for: Ihlas Bebou
🔍 [216/2530] Searching for: Rodrigo Becão
🔍 [217/2530] Searching for: Mads Bech Sørensen
🔍 [218/2530] Searching for: Julius Beck
🔍 [219/2530] Searching for: Sheraldo Becker
🔍 [220/2530] Searching for: Jan Bednarek
🔍 [221/2530] Searching for: Donny van de Beek
🔍 [222/2530] Searching for: Asmir Begovi?
🔍 [223/2530] Searching for: Yanis Begraoui
ℹ️ No injury data for Yanis Begraoui
🔍 [224/2530] Searching for: Kevin Behrens
🔍 [225/2530] Searching for: Alexis Beka Beka
🔍 [226/2530] Searching for: Jérémie Bela
🔍 [227/2530] Searching for: Youcef Belaïli
🔍 [228/2530] Searching for: Haris Belkebla
🔍 [229/2530] Searching for: Stefan Bell
🔍 [230/2530] Searching for: Armel Bella Kotchap
🔍 [231/2530] Searching for: Raoul Bellanova
🔍 [232/2530] Searching for: Karim Bellarabi
🔍 [233/2530] Searching for: Jean-Ricner Bellegarde
🔍 [234/2530] Searching for: Héctor Bellerín
🔍 [235/2530] Searching for: Jude Bellingham
🔍 [236/2530] Searching for: Jeanöel Belocian
⚠️ No Transfermarkt profile found for Jeanöel Belocian
🔍 [237/2530] Searching for: Andrea Belotti
🔍 [238/2530] Searching for: Fran Beltrán
🔍 [239/2530] Searching for: Eliesse Ben Seghir
🔍 [240/2530] Searching for: Salim Ben Seghir
🔍 [241/2530] Searching for: Wissam Ben Yedder
🔍 [242/2530] Searching for: Marco Benassi
🔍 [243/2530] Searching for: Ismaël Bennacer
🔍 [244/2530] Searching for: Saïd Benrahma
🔍 [245/2530] Searching for: Ramy Bensebaini
🔍 [246/2530] Searching for: Nabil Bentaleb
🔍 [247/2530] Searching for: Rodrigo Bentancur
🔍 [248/2530] Searching for: Karim Benzema
🔍 [249/2530] Searching for: Domenico Berardi
🔍 [250/2530] Searching for: Yuri Berchiche
🔍 [251/2530] Searching for: Álex Berenguer
🔍 [252/2530] Searching for: Bartosz Bereszy?ski
🔍 [253/2530] Searching for: Patrick Berg
🔍 [254/2530] Searching for: Mitchell van Bergen
🔍 [255/2530] Searching for: Mergim Berisha
🔍 [256/2530] Searching for: Quentin Bernard
ℹ️ No injury data for Quentin Bernard
🔍 [257/2530] Searching for: Paul Bernardoni
🔍 [258/2530] Searching for: Juan Bernat
🔍 [259/2530] Searching for: Victor Bernth Kristiansen
⚠️ No Transfermarkt profile found for Victor Bernth Kristiansen
🔍 [260/2530] Searching for: Jason Berthomier
🔍 [261/2530] Searching for: Beto
ℹ️ No injury data for Beto
🔍 [262/2530] Searching for: Owen Bevan
ℹ️ No injury data for Owen Bevan
🔍 [263/2530] Searching for: Matteo Bianchetti
❗ Error scraping Matteo Bianchetti: HTTPSConnectionPool(host='www.transfermarkt.com', port=443): Read timed out. (read timeout=10)
🔍 [264/2530] Searching for: Alessandro Bianco
🔍 [265/2530] Searching for: Giulian Biancone
🔍 [266/2530] Searching for: Ermin Bi?ak?i?
🔍 [267/2530] Searching for: Pedro Bigas
🔍 [268/2530] Searching for: Jaka Bijol
🔍 [269/2530] Searching for: El Bilal Touré
🔍 [270/2530] Searching for: Philip Billing
🔍 [271/2530] Searching for: Jean-Claude Billong
🔍 [272/2530] Searching for: Cristiano Biraghi
🔍 [273/2530] Searching for: Samuele Birindelli
🔍 [274/2530] Searching for: Veljko Birman?evi?
🔍 [275/2530] Searching for: Tom Bischof
🔍 [276/2530] Searching for: Yves Bissouma
🔍 [277/2530] Searching for: Kristijan Bistrovi?
🔍 [278/2530] Searching for: Leonardo Bittencourt

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time, random

# ===============================================
# 1️⃣ Load dataset and filter failed players
# ===============================================
df = pd.read_csv("player_injuries_all.csv")

error_mask = df['Injury'].astype(str).str.contains(
    "503|403|404|Error|timeout|Service Unavailable|Read timed out|No Profile|Failed",
    case=False, na=False
)
failed_players = df.loc[error_mask, 'Player'].dropna().unique().tolist()
print(f"🧩 Retrying {len(failed_players)} players with previous errors...")

# ===============================================
# 2️⃣ Helper: scrape injury data safely
# ===============================================
def get_injury_data(player_name, retries=3):
    headers = {"User-Agent": "Mozilla/5.0"}
    search_url = f"https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={player_name.replace(' ', '+')}"

    for attempt in range(retries):
        try:
            search_resp = requests.get(search_url, headers=headers, timeout=15)
            search_resp.raise_for_status()
            soup = BeautifulSoup(search_resp.text, "html.parser")

            # 🟩 Find the correct table containing player results
            table = soup.find("table", class_="items")
            if not table:
                return pd.DataFrame([{"Player": player_name, "Injury": "No Profile Found"}])

            # 🟩 Extract the first valid player link
            link_tag = None
            for a in table.find_all("a", href=True):
                if "/profil/spieler/" in a["href"]:
                    link_tag = a
                    break

            if not link_tag:
                return pd.DataFrame([{"Player": player_name, "Injury": "No Profile Found"}])

            profile_link = link_tag["href"]
            # Extract player_id safely
            try:
                player_id = profile_link.split("/")[-1]
                slug = profile_link.split("/profil/")[0]
            except Exception:
                return pd.DataFrame([{"Player": player_name, "Injury": "Malformed profile link"}])

            injury_url = f"https://www.transfermarkt.com{slug}/verletzungen/spieler/{player_id}"

            injury_resp = requests.get(injury_url, headers=headers, timeout=15)
            injury_resp.raise_for_status()
            soup_injury = BeautifulSoup(injury_resp.text, "html.parser")

            # 🩺 Parse the injury table
            table = soup_injury.find("table", class_="items")
            if not table:
                return pd.DataFrame([{"Player": player_name, "Injury": "No Injury Data"}])

            rows = table.find_all("tr", {"class": ["odd", "even"]})
            injury_data = []
            for row in rows:
                cols = [c.text.strip() for c in row.find_all("td")]
                if len(cols) >= 5:
                    injury_data.append({
                        "Player": player_name,
                        "Injury": cols[1],
                        "From": cols[2],
                        "Until": cols[3],
                        "Days": cols[4]
                    })

            if not injury_data:
                return pd.DataFrame([{"Player": player_name, "Injury": "No Injury Data"}])

            return pd.DataFrame(injury_data)

        except requests.exceptions.Timeout:
            print(f"⏳ Timeout for {player_name}, retry {attempt+1}/{retries}...")
            time.sleep(random.uniform(8, 15))
        except requests.exceptions.RequestException as e:
            print(f"⚠️ Request error for {player_name}: {e}")
            if attempt < retries - 1:
                time.sleep(random.uniform(8, 15))
                continue
            return pd.DataFrame([{"Player": player_name, "Injury": f"Error: {str(e)}"}])

    return pd.DataFrame([{"Player": player_name, "Injury": "Failed after retries"}])

# ===============================================
# 3️⃣ Retry only failed players
# ===============================================
retry_results = []
for i, player in enumerate(failed_players, start=1):
    print(f"🔁 [{i}/{len(failed_players)}] Retrying: {player}")
    df_player = get_injury_data(player)
    retry_results.append(df_player)
    time.sleep(random.uniform(6, 12))  # polite delay

# ===============================================
# 4️⃣ Merge new results with old dataset
# ===============================================
df_retry = pd.concat(retry_results, ignore_index=True)
df_cleaned = df[~df['Player'].isin(failed_players)]
df_final = pd.concat([df_cleaned, df_retry], ignore_index=True).drop_duplicates(subset=["Player", "Injury", "From"], keep="last")
df_final.to_csv("player_injuries_final_retry_fixed.csv", index=False)
print("✅ Retry complete! Fixed file saved as: player_injuries_final_retry_fixed.csv")

🧩 Retrying 151 players with previous errors...
🔁 [1/151] Retrying: Lorenz Assignon
🔁 [2/151] Retrying: Youcef Atal
🔁 [3/151] Retrying: Pierre-Emerick Aubameyang
🔁 [4/151] Retrying: Emil Audero
🔁 [5/151] Retrying: Tommaso Augello
🔁 [6/151] Retrying: Ludwig Augustinsson
🔁 [7/151] Retrying: Serge Aurier
🔁 [8/151] Retrying: Mathias Autret
🔁 [9/151] Retrying: Ezequiel Ávila
🔁 [10/151] Retrying: Cédric Avinel
🔁 [11/151] Retrying: Taiwo Awoniyi
🔁 [12/151] Retrying: Mehmet-Can Aydin
🔁 [13/151] Retrying: André Ayew
🔁 [14/151] Retrying: Jordan Ayew
🔁 [15/151] Retrying: Kaan Ayhan
🔁 [16/151] Retrying: Luke Ayling
🔁 [17/151] Retrying: Ayman Azhil
🔁 [18/151] Retrying: Sardar Azmoun
🔁 [19/151] Retrying: César Azpilicueta
⏳ Timeout for César Azpilicueta, retry 1/3...
🔁 [20/151] Retrying: Sanoussy Ba
🔁 [21/151] Retrying: Iddrisu Baba
🔁 [22/151] Retrying: Sr?an Babi?
🔁 [23/151] Retrying: Loïc Bade
🔁 [24/151] Retrying: Édgar Badía
🔁 [25/151] Retrying: Benoît Badiashile
🔁 [26/151] Retrying: Alex Baena
🔁 [27/151] Retrying: Jaime Báez
🔁 [28/151] Retrying: Leon Bailey
🔁 [29/151] Retrying: Eric Bailly
🔁 [30/151] Retrying: Dénys Bain
🔁 [31/151] Retrying: Brandon Baiye
🔁 [32/151] Retrying: Stefan Bajcetic
🔁 [33/151] Retrying: Nedim Bajrami
🔁 [34/151] Retrying: Cédric Bakambu
🔁 [35/151] Retrying: Mitchel Bakker
🔁 [36/151] Retrying: Ridle Baku
🔁 [37/151] Retrying: Tommaso Baldanzi
🔁 [38/151] Retrying: Alejandro Balde
🔁 [39/151] Retrying: Thierno Balde
🔁 [40/151] Retrying: Carlos Baleba
🔁 [41/151] Retrying: Mikel Balenziaga
🔁 [42/151] Retrying: Leonardo Balerdi
🔁 [43/151] Retrying: Fodé Ballo-Touré
🔁 [44/151] Retrying: Matteo Bianchetti
🔁 [45/151] Retrying: Antonin Bobichon
🔁 [46/151] Retrying: Mikkel Damsgaard
🔁 [47/151] Retrying: Cyriel Dessers
🔁 [48/151] Retrying: Eric Dier
🔁 [49/151] Retrying: Kyliane Dong
🔁 [50/151] Retrying: Ondrej Duda
🔁 [51/151] Retrying: Maxime Estève
🔁 [52/151] Retrying: Pervis Estupiñán
🔁 [53/151] Retrying: Edu Expósito
🔁 [54/151] Retrying: ?ukasz Fabia?ski
🔁 [55/151] Retrying: João Félix
🔁 [56/151] Retrying: Idrissa Gana Gueye
🔁 [57/151] Retrying: David García
⏳ Timeout for David García, retry 1/3...
🔁 [58/151] Retrying: Joe Gelhardt
🔁 [59/151] Retrying: Patrick Herrmann
🔁 [60/151] Retrying: Adam Hlo?ek
🔁 [61/151] Retrying: Philipp Hofmann
🔁 [62/151] Retrying: Rareþ Ilie
🔁 [63/151] Retrying: Marcus Ingvartsen
🔁 [64/151] Retrying: Ardian Ismajli
🔁 [65/151] Retrying: Ben Johnson
🔁 [66/151] Retrying: Josan
🔁 [67/151] Retrying: Willian José
🔁 [68/151] Retrying: Joselu
🔁 [69/151] Retrying: Diogo Jota
🔁 [70/151] Retrying: Stevan Joveti?
🔁 [71/151] Retrying: Luka Jovi?
🔁 [72/151] Retrying: Juanmi
🔁 [73/151] Retrying: Juanpe
🔁 [74/151] Retrying: Jubal
🔁 [75/151] Retrying: Christopher Jullien
🔁 [76/151] Retrying: Anthony Jung
🔁 [77/151] Retrying: Lago Junior
🔁 [78/151] Retrying: Hamed Junior Traorè
🔁 [79/151] Retrying: Vinicius Júnior
⏳ Timeout for Vinicius Júnior, retry 1/3...
🔁 [80/151] Retrying: Josip Juranovi?
🔁 [81/151] Retrying: James Justin
🔁 [82/151] Retrying: Mathias Jørgensen
🔁 [83/151] Retrying: Ozan Kabak
🔁 [84/151] Retrying: Issa Kaboré
🔁 [85/151] Retrying: Abdoul Kader Bamba
🔁 [86/151] Retrying: Pavel Kade?ábek
🔁 [87/151] Retrying: Tino Kadewere
🔁 [88/151] Retrying: Kaiky
🔁 [89/151] Retrying: Florian Kainz
🔁 [90/151] Retrying: Gaël Kakuta
🔁 [91/151] Retrying: Sasa Kalajdzic
🔁 [92/151] Retrying: Arnaud Kalimuendo
🔁 [93/151] Retrying: Yayah Kallon
🔁 [94/151] Retrying: Felix Kalu Nmecha
🔁 [95/151] Retrying: Gedeon Kalulu
🔁 [96/151] Retrying: Pierre Kalulu
🔁 [97/151] Retrying: Daichi Kamada
🔁 [98/151] Retrying: Waren Kamanzi
🔁 [99/151] Retrying: Bingourou Kamara
🔁 [100/151] Retrying: Boubacar Kamara
🔁 [101/151] Retrying: Jakub Kami?ski
🔁 [102/151] Retrying: Marcin Kami?ski
🔁 [103/151] Retrying: Kevin Kampl
🔁 [104/151] Retrying: Nordine Kandil
🔁 [105/151] Retrying: Harry Kane
🔁 [106/151] Retrying: Wilfried Kanga
🔁 [107/151] Retrying: Lee Kangin
🔁 [108/151] Retrying: N'Golo Kanté
🔁 [109/151] Retrying: Kenan Karaman
🔁 [110/151] Retrying: Yann Karamoh
🔁 [111/151] Retrying: Atakan Karazor
🔁 [112/151] Retrying: Jon Karrikaburu
🔁 [113/151] Retrying: Rick Karsdorp
🔁 [114/151] Retrying: Denso Kasius
🔁 [115/151] Retrying: Grigoris Kastanos
🔁 [116/151] Retrying: Silas Katompa
🔁 [117/151] Retrying: Moise Kean
🔁 [118/151] Retrying: Michael Keane
🔁 [119/151] Retrying: Emil Krafth
🔁 [120/151] Retrying: Léo Leroy
🔁 [121/151] Retrying: Robert Lewandowski
🔁 [122/151] Retrying: Sebastiano Luperto
🔁 [123/151] Retrying: Enzo Millot
🔁 [124/151] Retrying: Kaoru Mitoma
🔁 [125/151] Retrying: Benjamin Pavard
🔁 [126/151] Retrying: Ronaël Pierre-Gabriel
🔁 [127/151] Retrying: Andrea Pinamonti
🔁 [128/151] Retrying: Gerard Piqué
🔁 [129/151] Retrying: Fabio Quagliarella
🔁 [130/151] Retrying: Jacob Ramsey
🔁 [131/151] Retrying: Ante Rebi?
🔁 [132/151] Retrying: Pepe Reina
🔁 [133/151] Retrying: Marco Richter
🔁 [134/151] Retrying: Manuel Riemann
🔁 [135/151] Retrying: Dani Rodríguez
🔁 [136/151] Retrying: Sebastian Rudy
🔁 [137/151] Retrying: Leandro Sanca
🔁 [138/151] Retrying: Stefan Savi?
⏳ Timeout for Stefan Savi?, retry 1/3...
⏳ Timeout for Stefan Savi?, retry 2/3...
🔁 [139/151] Retrying: Fabian Schär
🔁 [140/151] Retrying: Kingsley Schindler
🔁 [141/151] Retrying: Nico Schlotterbeck
🔁 [142/151] Retrying: Unai Simón
🔁 [143/151] Retrying: Chris Smalling
🔁 [144/151] Retrying: Adam Smith
🔁 [145/151] Retrying: Matìas Soulé
🔁 [146/151] Retrying: Dyego Sousa
🔁 [147/151] Retrying: Nuno Tavares
🔁 [148/151] Retrying: Darlin Yongwa
🔁 [149/151] Retrying: Maya Yoshida
🔁 [150/151] Retrying: Simon Zoller
🔁 [151/151] Retrying: Kurt Zouma
✅ Retry complete! Fixed file saved as: player_injuries_final_retry_fixed.csv

In [ ]:
import pandas as pd
from datetime import datetime

# Load your full injury dataset
df_inj = pd.read_csv("player_injuries_final_retry_fixed.csv")

# Clean "Days" column (convert "36 days" → 36)
df_inj["Days_clean"] = (
    df_inj["Days"]
    .fillna("0")
    .str.replace(" days", "")
    .str.replace(" day", "")
    .replace("-", "0")
    .astype(int)
)

# Convert "From" and "Until" columns to datetime (if available)
for col in ["From", "Until"]:
    df_inj[col] = pd.to_datetime(df_inj[col], errors="coerce", dayfirst=True)

# Compute aggregated injury features per player
df_summary = df_inj.groupby("Player").agg(
    total_injuries=("Injury", "count"),
    total_days_injured=("Days_clean", "sum"),
    avg_days_injured=("Days_clean", "mean"),
    max_days_injured=("Days_clean", "max"),
    recent_injury_days=("Days_clean", "first")  # optional — most recent injury
).reset_index()

# Fill missing values with 0
df_summary = df_summary.fillna(0)

# Save aggregated injury summary
df_summary.to_csv("player_injury_summary.csv", index=False)

print("✅ Injury summary saved as player_injury_summary.csv")

✅ Injury summary saved as player_injury_summary.csv

In [ ]:
 import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# 🧍 Choose one player name
player = "Brenden Aaronson"   # 🔁 change this name to test another player

base_search_url = "https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query="
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
}

try:
    print(f"🔍 Searching for player: {player}")
    search_url = base_search_url + player.replace(" ", "+")
    response = requests.get(search_url, headers=headers)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")

    # Find player profile link
    link_tag = None
    for a in soup.find_all("a", href=True):
        if "/profil/spieler/" in a["href"]:
            link_tag = a
            break

    if not link_tag:
        print(f"⚠️ No Transfermarkt profile found for {player}")
    else:
        href = link_tag["href"]
        slug = href.split("/")[1]
        player_id = href.split("/spieler/")[-1]
        injury_url = f"https://www.transfermarkt.com/{slug}/verletzungen/spieler/{player_id}"
        print(f"📄 Player injury page: {injury_url}")

        injury_resp = requests.get(injury_url, headers=headers)
        injury_soup = BeautifulSoup(injury_resp.text, "html.parser")

        # Locate injury table
        table = injury_soup.find("table", class_="items")

        if not table:
            print(f"❌ No injury data found for {player}")
        else:
            # Parse rows
            rows = table.find_all("tr", class_=["odd", "even"])
            injury_data = []
            for row in rows:
                cols = [td.text.strip() for td in row.find_all("td")]
                if len(cols) >= 5:
                    injury_data.append({
                        "Player": player,
                        "Injury": cols[1],
                        "From": cols[2],
                        "Until": cols[3],
                        "Days": cols[4]
                    })

            # Convert to DataFrame
            df_inj = pd.DataFrame(injury_data)
            print("\n✅ Injury Data Extracted:")
            print(df_inj)

except Exception as e:
    print(f"❗ Error: {e}")

🔍 Searching for player: Brenden Aaronson
📄 Player injury page: https://www.transfermarkt.com/brenden-aaronson/verletzungen/spieler/393323

✅ Injury Data Extracted:
             Player         Injury        From       Until     Days
0  Brenden Aaronson            Ill  24/11/2023  27/11/2023   4 days
1  Brenden Aaronson  Knee problems  19/03/2022  23/04/2022  36 days

DATA CLEANING

In [ ]:
import pandas as pd

# Load the data
df = pd.read_csv("/content/2022-2023 Football Player Stats.csv", delimiter=';', encoding='latin1')

# Overview
df.info()
df.head()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2689 entries, 0 to 2688
Columns: 124 entries, Rk to AerWon%
dtypes: float64(112), int64(7), object(5)
memory usage: 2.5+ MB

,Rk,Age,Born,MP,Starts,Min,90s,Goals,Shots,SoT,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
count,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,...,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000,2689.000000
mean,1345.000000,26.011157,1996.155820,11.833023,8.476013,760.451097,8.450465,1.027520,1.245787,0.411261,...,0.204697,1.661636,0.990569,0.009249,0.015173,0.003142,4.951967,1.312064,1.497356,43.583600
std,776.391761,4.446259,4.450108,6.864278,6.994383,591.094260,6.567484,2.013714,1.424619,0.754716,...,0.552376,2.319000,1.235965,0.043781,0.077399,0.022607,2.901833,1.579539,1.830391,26.673092
min,1.000000,15.000000,1981.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,673.000000,23.000000,1993.000000,5.000000,2.000000,194.000000,2.200000,0.000000,0.260000,0.000000,...,0.000000,0.000000,0.300000,0.000000,0.000000,0.000000,3.330000,0.330000,0.550000,27.600000
50%,1345.000000,26.000000,1996.000000,13.000000,7.000000,684.000000,7.600000,0.000000,0.860000,0.180000,...,0.000000,0.760000,0.830000,0.000000,0.000000,0.000000,5.000000,0.930000,1.100000,46.400000
75%,2017.000000,29.000000,2000.000000,18.000000,14.000000,1245.000000,13.800000,1.000000,1.850000,0.590000,...,0.210000,2.500000,1.320000,0.000000,0.000000,0.000000,6.270000,1.790000,1.830000,60.000000
max,2689.000000,41.000000,2007.000000,23.000000,23.000000,2070.000000,23.000000,25.000000,15.000000,10.000000,...,10.000000,30.000000,20.000000,0.870000,2.000000,0.500000,30.000000,25.000000,30.000000,100.000000

In [ ]:
df.drop(columns=['Rk'], inplace=True, errors='ignore')

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(2689, 123)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Nation     1
Player     0
Pos        0
Squad      0
Comp       0
          ..
OG         0
Recov      0
AerWon     0
AerLost    0
AerWon%    0
Length: 123, dtype: int64

In [ ]:
df['Nation'] = df['Nation'].fillna(df['Nation'].mode()[0])

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Player     0
Nation     0
Pos        0
Squad      0
Comp       0
          ..
OG         0
Recov      0
AerWon     0
AerLost    0
AerWon%    0
Length: 123, dtype: int64

In [ ]:
#5️ Convert Data Types
numeric_cols = df.columns.drop(['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Born'])
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
#6 Clean Percentage Columns
percent_cols = [col for col in df.columns if df[col].astype(str).str.contains('%').any()]
for col in percent_cols:
    df[col] = df[col].astype(str).str.replace('%','').astype(float)

In [ ]:
#7 Normalize Column Names
df.columns = (df.columns
                .str.strip()
                .str.replace(' ', '_')
                .str.replace('%', 'pct')
                .str.replace('+', '_plus_')
                .str.lower())

In [ ]:
#8 Fix Categorical Fields
for col in ['player', 'nation', 'pos', 'squad', 'comp']:
    df[col] = df[col].str.strip().str.title()

In [ ]:
#9 Feature Engineering (Optional)
df['goals_per90'] = df['goals'] / df['90s']
df['assists_per90'] = df['assists'] / df['90s']
df['shots_on_target_rate'] = df['sot'] / df['shots']

/tmp/ipython-input-4017916828.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['goals_per90'] = df['goals'] / df['90s']
/tmp/ipython-input-4017916828.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['assists_per90'] = df['assists'] / df['90s']
/tmp/ipython-input-4017916828.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['shots_on_target_rate'] = df['sot'] / df['shots']

In [ ]:
df = df.copy()

In [ ]:
#10 Outlier Detection
df = df[(df['sot'] <= 100) & (df['age'] < 45)]

In [ ]:
df.shape

(2689, 126)

In [ ]:
import numpy as np

# 1. Replace infinities with NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# 2. Fill numeric NaN with 0
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(0)

# 3. Fill text NaN with 'Unknown'
str_cols = df.select_dtypes(include=['object']).columns
df[str_cols] = df[str_cols].fillna('Unknown')

# 4. Verify
print(df.isna().sum().sort_values(ascending=False).head(10))

player    0
nation    0
pos       0
squad     0
comp      0
age       0
born      0
mp        0
starts    0
min       0
dtype: int64

In [ ]:
df.isnull().sum().sort_values(ascending=False)

player                  0
nation                  0
pos                     0
squad                   0
comp                    0
                       ..
aerlost                 0
aerwonpct               0
goals_per90             0
assists_per90           0
shots_on_target_rate    0
Length: 126, dtype: int64

In [ ]:
df.to_csv("clean_player_performance.csv", index=False)

In [ ]:
!pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 17.3 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

In [ ]:
import pandas as pd
import re
from unidecode import unidecode

# ======================================
# 1️⃣ Load the two datasets
# ======================================
main_df = pd.read_csv("player_data_with_reddit_sentiment.csv")   # your main dataset
secondary_df = pd.read_csv("player_injury_summary.csv")          # dataset to merge (e.g., injury)

# ======================================
# 2️⃣ Define the cleaning function
# ======================================
def clean_text(name):
    if pd.isna(name):
        return ""
    name = unidecode(str(name).lower().strip())
    name = re.sub(r'[^a-z\s]', '', name)  # keep only letters and spaces
    name = re.sub(r'\s+', ' ', name)      # collapse multiple spaces
    return name.title()

# ======================================
# 3️⃣ Clean the player names in both datasets
# ======================================
main_df["player_clean"] = main_df["Player"].apply(clean_text)
secondary_df["player_clean"] = secondary_df["Player"].apply(clean_text)

# ======================================
# 4️⃣ Merge on the cleaned player name
# ======================================
merged = main_df.merge(secondary_df, on="player_clean", how="left")

# ======================================
# 5️⃣ Save the merged dataset
# ======================================
merged.to_csv("merged_player_data.csv", index=False)

# ======================================
# 6️⃣ Verify result
# ======================================
print("✅ Merge completed successfully!")
print("Main dataset shape:", main_df.shape)
print("Secondary dataset shape:", secondary_df.shape)
print("Merged dataset shape:", merged.shape)
print("\nSample merged data:")
print(merged[["Player_x", "Player_y", "player_clean"]].head(10))

✅ Merge completed successfully!
Main dataset shape: (2415, 135)
Secondary dataset shape: (2530, 7)
Merged dataset shape: (2417, 141)

Sample merged data:
            Player_x           Player_y       player_clean
0   Brenden Aaronson   Brenden Aaronson   Brenden Aaronson
1   Yunis Abdelhamid   Yunis Abdelhamid   Yunis Abdelhamid
2      Himad Abdelli      Himad Abdelli      Himad Abdelli
3  Salis Abdul Samed  Salis Abdul Samed  Salis Abdul Samed
4    Laurent Abergel    Laurent Abergel    Laurent Abergel
5  Oliver Abildgaard  Oliver Abildgaard  Oliver Abildgaard
6     Matthis Abline     Matthis Abline     Matthis Abline
7     Matthis Abline     Matthis Abline     Matthis Abline
8              Abner              Abner              Abner
9  Zakaria Aboukhlal  Zakaria Aboukhlal  Zakaria Aboukhlal

In [ ]:
import pandas as pd

# Load your merged dataset
merged = pd.read_csv("merged_player_data.csv")

# Drop redundant/duplicate columns
columns_to_drop = [
    "Player_x", "Player_y", "Player",
    "Market Value", "Market Value_x", "Market Value_y",
    "Market Value Euros_x", "Market Value Euros_y",
    "PasCmp", "PasAtt", "Crs", "TklW"
]

merged.drop(columns=columns_to_drop, errors="ignore", inplace=True)

# Keep only cleaned player name for reference
if "player_clean" in merged.columns:
    merged.rename(columns={"player_clean": "player_id"}, inplace=True)

# Save ML-ready dataset
merged.to_csv("player_data_ml_ready.csv", index=False)

print("✅ ML-ready dataset saved as 'player_data_ml_ready.csv'")
print("Final shape:", merged.shape)

✅ ML-ready dataset saved as 'player_data_ml_ready.csv'
Final shape: (2417, 130)

In [ ]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("player_data_ml_ready.csv")

# 1️⃣ Drop unnecessary and duplicate rows
df.drop(columns=['Rk'], inplace=True, errors='ignore')
df.drop_duplicates(inplace=True)

# 2️⃣ Fill missing values
if 'Nation' in df.columns:
    df['Nation'] = df['Nation'].fillna(df['Nation'].mode()[0])

# 3️⃣ Convert numeric columns
non_numeric = ['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Born']
numeric_cols = [c for c in df.columns if c not in non_numeric]
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# 4️⃣ Handle percentage-like columns safely
percent_cols = [c for c in df.columns if df[c].dtype == 'object' and df[c].astype(str).str.contains('%').any()]
for col in percent_cols:
    df[col] = df[col].astype(str).str.replace('%', '', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 5️⃣ Normalize column names
df.columns = (df.columns
              .str.strip()
              .str.replace(' ', '_')
              .str.replace('%', 'pct')
              .str.replace('+', '_plus_')
              .str.lower())

# 6️⃣ Standardize categorical columns
for col in ['player', 'nation', 'pos', 'squad', 'comp']:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.lower()

# 7️⃣ Feature Engineering (guard against division by zero)
if '90s' in df.columns:
    df['goals_per90'] = df['goals'] / df['90s'].replace(0, np.nan)
    df['assists_per90'] = df['assists'] / df['90s'].replace(0, np.nan)
    df['shots_on_target_rate'] = df['sot'] / df['shots'].replace(0, np.nan)

# 8️⃣ Handle infinities, NaNs, and outliers
df.replace([np.inf, -np.inf], np.nan, inplace=True)
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(0)
str_cols = df.select_dtypes(include=['object']).columns
df[str_cols] = df[str_cols].fillna('unknown')

# Optional: Outlier removal using quantiles instead of fixed values
if 'sot' in df.columns and 'age' in df.columns:
    df = df[df['sot'] <= df['sot'].quantile(0.99)]
    df = df[df['age'] <= df['age'].quantile(0.99)]

# 9️⃣ Save cleaned dataset
df.to_csv("final_dataset.csv", index=False)
print("✅ Cleaned dataset saved as 'clean_player_performance.csv'")
print("Final shape:", df.shape)
print(df.isna().sum().sort_values(ascending=False).head(10))

/tmp/ipython-input-241765660.py:41: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['goals_per90'] = df['goals'] / df['90s'].replace(0, np.nan)
/tmp/ipython-input-241765660.py:42: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['assists_per90'] = df['assists'] / df['90s'].replace(0, np.nan)
/tmp/ipython-input-241765660.py:43: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['shots_on_target_rate'] = df['sot'] / df['shots'].replace(0, np.nan)

✅ Cleaned dataset saved as 'clean_player_performance.csv'
Final shape: (2380, 132)
nation    0
pos       0
squad     0
comp      0
age       0
born      0
mp        0
starts    0
min       0
90s       0
dtype: int64

In [ ]:
# ===============================================================
# ⚙️ PLAYER MARKET VALUE FEATURE ENGINEERING PIPELINE
# ===============================================================
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("final_dataset.csv")

# ---------------------------------------------------------------
# 🧹 1. Column normalization and cleanup
# ---------------------------------------------------------------
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df = df.copy()

# Handle missing / invalid entries
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)

# ---------------------------------------------------------------
# 🧩 2. Basic Efficiency Metrics
# ---------------------------------------------------------------
if 'goals' in df.columns and '90s' in df.columns:
    df['goals_per90'] = df['goals'] / df['90s'].replace(0, np.nan)
if 'assists' in df.columns and '90s' in df.columns:
    df['assists_per90'] = df['assists'] / df['90s'].replace(0, np.nan)
if {'goals', 'assists', '90s'}.issubset(df.columns):
    df['goal_contrib_per90'] = (df['goals'] + df['assists']) / df['90s'].replace(0, np.nan)

# ---------------------------------------------------------------
# 🎯 3. Shooting & Passing
# ---------------------------------------------------------------
if {'sot', 'shots'}.issubset(df.columns):
    df['shots_on_target_rate'] = df['sot'] / df['shots'].replace(0, np.nan)
if {'pastotcmp', 'pastotatt'}.issubset(df.columns):
    df['pass_accuracy'] = df['pastotcmp'] / df['pastotatt'].replace(0, np.nan)
if {'pasprog', 'pastotatt'}.issubset(df.columns):
    df['progressive_pass_rate'] = df['pasprog'] / df['pastotatt'].replace(0, np.nan)

# ---------------------------------------------------------------
# 🛡️ 4. Defensive & Physical Features
# ---------------------------------------------------------------
defense_cols = [c for c in ['tkl', 'int', 'blocks'] if c in df.columns]
if defense_cols:
    df['defensive_actions'] = df[defense_cols].sum(axis=1)

if {'crdy', 'crdr'}.issubset(df.columns):
    df['discipline_score'] = df['crdy'] + (2 * df['crdr'])

if {'stamina', 'strength', 'jumping'}.issubset(df.columns):
    df['physical_strength'] = (df['stamina'] + df['strength'] + df['jumping']) / 3

# ---------------------------------------------------------------
# 🩺 5. Injury-Related Features
# ---------------------------------------------------------------
if {'total_injuries', 'total_days_injured'}.issubset(df.columns):
    df['avg_days_per_injury'] = df['total_days_injured'] / df['total_injuries'].replace(0, np.nan)
    df['injury_ratio'] = df['total_injuries'] / (df['90s'] + 1)

# ---------------------------------------------------------------
# 💬 6. Sentiment-Based Features
# ---------------------------------------------------------------
if {'positive', 'neutral', 'negative'}.issubset(df.columns):
    df['net_sentiment'] = df['positive'] - df['negative']
    df['sentiment_ratio'] = (df['positive'] + 1) / (df['negative'] + 1)

# ---------------------------------------------------------------
# 📊 7. Composite Feature Scores (inspired by notebook logic)
# ---------------------------------------------------------------
if {'goals_per90', 'assists_per90', 'pass_accuracy', 'shots_on_target_rate'}.issubset(df.columns):
    df['offensive_index'] = (
        0.4 * df['goals_per90'] +
        0.3 * df['assists_per90'] +
        0.2 * df['pass_accuracy'] +
        0.1 * df['shots_on_target_rate']
    )

if {'defensive_actions', 'discipline_score'}.issubset(df.columns):
    df['defensive_index'] = df['defensive_actions'] / (df['discipline_score'] + 1)

if {'physical_strength', 'defensive_index', 'offensive_index'}.issubset(df.columns):
    df['total_player_index'] = (
        0.5 * df['offensive_index'] +
        0.3 * df['defensive_index'] +
        0.2 * df['physical_strength']
    )

# ---------------------------------------------------------------
# 🔍 8. Normalize numeric columns (optional scaling)
# ---------------------------------------------------------------
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].apply(lambda x: (x - x.mean()) / (x.std() + 1e-8))

# ---------------------------------------------------------------
# 💾 9. Save engineered dataset
# ---------------------------------------------------------------
output_path = "final_dataset_feature_engineered.csv"
df.to_csv(output_path, index=False)

print("✅ Feature Engineering Completed Successfully!")
print("Saved as:", output_path)
print("Total features:", df.shape[1])

# Show sample engineered features
feature_cols = [
    'goals_per90', 'assists_per90', 'goal_contrib_per90',
    'shots_on_target_rate', 'pass_accuracy', 'progressive_pass_rate',
    'defensive_actions', 'discipline_score', 'physical_strength',
    'avg_days_per_injury', 'net_sentiment', 'sentiment_ratio',
    'offensive_index', 'defensive_index', 'total_player_index'
]
available = [c for c in feature_cols if c in df.columns]
print("\nEngineered Features:", available)
df[available].head(10)

✅ Feature Engineering Completed Successfully!
Saved as: final_dataset_feature_engineered.csv
Total features: 143

Engineered Features: ['goals_per90', 'assists_per90', 'goal_contrib_per90', 'shots_on_target_rate', 'pass_accuracy', 'progressive_pass_rate', 'defensive_actions', 'discipline_score', 'avg_days_per_injury', 'net_sentiment', 'sentiment_ratio', 'offensive_index', 'defensive_index']

,goals_per90,assists_per90,goal_contrib_per90,shots_on_target_rate,pass_accuracy,progressive_pass_rate,defensive_actions,discipline_score,avg_days_per_injury,net_sentiment,sentiment_ratio,offensive_index,defensive_index
0,-0.260489,-0.049499,-0.137618,-0.493886,-0.116812,0.418562,-0.078344,-0.205342,-0.501406,1.365442,1.446933,-0.441299,0.030070
1,-0.532791,-0.056544,-0.239372,-1.042824,0.484004,0.281825,1.201662,-0.229504,-0.737780,-1.183204,-1.096227,-0.637410,1.350596
2,-0.532791,-0.060606,-0.243199,0.166977,0.416171,0.825985,0.672797,-0.193261,-0.678687,-2.455482,-1.892317,-0.419735,0.759148
3,-0.291804,-0.060606,-0.159020,-0.199371,1.386841,0.136748,0.117106,-0.157019,0.732172,-0.870940,-0.864855,-0.132495,0.172798
4,-0.532791,-0.049522,-0.232758,-1.298415,0.998239,0.615015,1.059865,-0.144938,-0.506330,-1.124193,-1.042073,-0.578229,1.057923
5,-0.532791,-0.060606,-0.243199,NaN,-0.846464,-1.246117,2.454842,-0.338230,-0.261749,-1.474809,-1.307235,NaN,2.969669
6,1.762320,-0.060606,0.558506,0.166977,-0.423842,1.798902,-0.461580,-0.338230,NaN,-0.398139,-0.502390,1.056122,-0.250965
7,3.483654,-0.060606,1.159784,0.169908,-2.634571,0.895012,-0.101338,-0.338230,NaN,-0.398139,-0.502390,1.859167,0.146853
8,-0.532791,-0.060606,-0.243199,0.866866,-0.386055,-0.263281,0.921900,-0.338230,-0.402917,-0.305732,-0.402188,-0.437355,1.276826
9,0.910243,-0.034921,0.285062,0.332167,-0.587663,-0.105898,-0.411759,-0.120777,0.217566,-0.758463,-0.840658,0.485963,-0.358633

SENTIMENT ANALYSIS

In [ ]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2025.10.5)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 4.5 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# ===============================
# 1️⃣ Load the Reddit Sentiment Data
# ===============================
df = pd.read_csv("reddit_sentiment_data.csv")

print("Before cleaning:", df.shape)
df.head()

# ===============================
# 2️⃣ Basic Cleaning
# ===============================

# Drop rows with missing or empty text
df = df[df["Text"].notna()]
df = df[df["Text"].str.strip() != ""]

# Remove duplicates
df = df.drop_duplicates(subset=["Player", "Text"])

# Remove extremely short or meaningless posts
df = df[df["Text"].str.len() > 20]

print("After cleaning:", df.shape)

# ===============================
# 3️⃣ Recompute Sentiment (Optional)
# ===============================
# In case the earlier sentiment scores were noisy or missing
analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    score = analyzer.polarity_scores(text)["compound"]
    if score > 0.05:
        return "positive", score
    elif score < -0.05:
        return "negative", score
    else:
        return "neutral", score

df[["Sentiment", "SentimentScore"]] = df["Text"].apply(
    lambda t: pd.Series(get_sentiment(t))
)

# ===============================
# 4️⃣ Aggregate Sentiment Per Player
# ===============================
sentiment_summary = (
    df.groupby("Player")["Sentiment"]
    .value_counts(normalize=True)
    .unstack(fill_value=0)
)

sentiment_summary["AvgSentimentScore"] = df.groupby("Player")["SentimentScore"].mean()
sentiment_summary.reset_index(inplace=True)

print("✅ Sentiment summary created:")
print(sentiment_summary.head())

# ===============================
# 5️⃣ Save Cleaned + Summary Data
# ===============================
'''df.to_csv("reddit_sentiment_cleaned.csv", index=False)
sentiment_summary.to_csv("reddit_sentiment_summary.csv", index=False)

print("✅ Cleaned data saved as reddit_sentiment_cleaned.csv")
print("✅ Sentiment summary saved as reddit_sentiment_summary.csv")'''

Before cleaning: (143950, 4)
After cleaning: (143856, 4)
✅ Sentiment summary created:
Sentiment                 Player  negative   neutral  positive  \
0          ?órir Jóhann Helgason  0.470588  0.000000  0.529412
1                Aaron Cresswell  0.102564  0.102564  0.794872
2                   Aaron Hickey  0.370370  0.185185  0.444444
3                 Aaron Ramsdale  0.410000  0.170000  0.420000
4                   Aaron Ramsey  0.240000  0.350000  0.410000

Sentiment  AvgSentimentScore
0                   0.125700
1                   0.624788
2                   0.023639
3                   0.003236
4                   0.105102

'df.to_csv("reddit_sentiment_cleaned.csv", index=False)\nsentiment_summary.to_csv("reddit_sentiment_summary.csv", index=False)\n\nprint("✅ Cleaned data saved as reddit_sentiment_cleaned.csv")\nprint("✅ Sentiment summary saved as reddit_sentiment_summary.csv")'

In [ ]:
df.to_csv("reddit_sentiment_cleaned.csv", index=False)
sentiment_summary.to_csv("reddit_sentiment_summary.csv", index=False)

print("✅ Cleaned data saved as reddit_sentiment_cleaned.csv")
print("✅ Sentiment summary saved as reddit_sentiment_summary.csv")

✅ Cleaned data saved as reddit_sentiment_cleaned.csv
✅ Sentiment summary saved as reddit_sentiment_summary.csv