DATA COLLECTION $ EXPLORING- WEEK 1

In [2]:
import pandas as pd

# Load the dataset
file_path = '/fifa_players.csv'  #Path of the csv file
df = pd.read_csv(file_path)

# Summary stats
total_rows = df.shape[0]
total_columns = df.shape[1]
column_names = df.columns.tolist()
data_types = df.dtypes
missing_values = df.isnull().sum()
sample_values = df.head(1).to_dict(orient='records')[0]

# Print summary
print("FIFA Players Dataset Summary")
print(f"Total Rows: {total_rows}")
print(f"Total Columns: {total_columns}\n")

print(" Column Details:")
for col in column_names:
    print(f"- {col}")
print("\n Column Breakdown:")
for col in column_names:
    print(f"{col}:")
    print(f"  - Data Type: {data_types[col]}")
    print(f"  - Missing Values: {missing_values[col]}")
    print(f"  - Sample Value: {sample_values.get(col, 'N/A')}\n")

FIFA Players Dataset Summary
Total Rows: 17954
Total Columns: 51

 Column Details:
- name
- full_name
- birth_date
- age
- height_cm
- weight_kgs
- positions
- nationality
- overall_rating
- potential
- value_euro
- wage_euro
- preferred_foot
- international_reputation(1-5)
- weak_foot(1-5)
- skill_moves(1-5)
- body_type
- release_clause_euro
- national_team
- national_rating
- national_team_position
- national_jersey_number
- crossing
- finishing
- heading_accuracy
- short_passing
- volleys
- dribbling
- curve
- freekick_accuracy
- long_passing
- ball_control
- acceleration
- sprint_speed
- agility
- reactions
- balance
- shot_power
- jumping
- stamina
- strength
- long_shots
- aggression
- interceptions
- positioning
- vision
- penalties
- composure
- marking
- standing_tackle
- sliding_tackle

 Column Breakdown:
name:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: L. Messi

full_name:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: Lionel Andrés Messi Cuccittini

birth_date:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: 6/24/1987

age:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 31

height_cm:
  - Data Type: float64
  - Missing Values: 0
  - Sample Value: 170.18

weight_kgs:
  - Data Type: float64
  - Missing Values: 0
  - Sample Value: 72.1

positions:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: CF,RW,ST

nationality:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: Argentina

overall_rating:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 94

potential:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 94

value_euro:
  - Data Type: float64
  - Missing Values: 255
  - Sample Value: 110500000.0

wage_euro:
  - Data Type: float64
  - Missing Values: 246
  - Sample Value: 565000.0

preferred_foot:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: Left

international_reputation(1-5):
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 5

weak_foot(1-5):
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 4

skill_moves(1-5):
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 4

body_type:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: Messi

release_clause_euro:
  - Data Type: float64
  - Missing Values: 1837
  - Sample Value: 226500000.0

national_team:
  - Data Type: object
  - Missing Values: 17097
  - Sample Value: Argentina

national_rating:
  - Data Type: float64
  - Missing Values: 17097
  - Sample Value: 82.0

national_team_position:
  - Data Type: object
  - Missing Values: 17097
  - Sample Value: RF

national_jersey_number:
  - Data Type: float64
  - Missing Values: 17097
  - Sample Value: 10.0

crossing:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 86

finishing:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 95

heading_accuracy:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 70

short_passing:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 92

volleys:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 86

dribbling:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 97

curve:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 93

freekick_accuracy:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 94

long_passing:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 89

ball_control:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 96

acceleration:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 91

sprint_speed:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 86

agility:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 93

reactions:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 95

balance:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 95

shot_power:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 85

jumping:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 68

stamina:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 72

strength:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 66

long_shots:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 94

aggression:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 48

interceptions:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 22

positioning:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 94

vision:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 94

penalties:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 75

composure:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 96

marking:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 33

standing_tackle:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 28

sliding_tackle:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 26

INJURY DATASET

In [23]:
import pandas as pd

# Load the dataset
file_path = '/dataset.csv'
df = pd.read_csv(file_path)

# Summary stats
total_rows = df.shape[0]
total_columns = df.shape[1]
column_names = df.columns.tolist()
data_types = df.dtypes
missing_values = df.isnull().sum()
sample_values = df.head(1).to_dict(orient='records')[0]

# Print summary
print("FIFA Players Dataset Summary")
print(f"Total Rows: {total_rows}")
print(f"Total Columns: {total_columns}\n")
print(" Column Details:")
for col in column_names:
    print(f"- {col}")

FIFA Players Dataset Summary
Total Rows: 1301
Total Columns: 30

 Column Details:
- p_id2
- start_year
- season_days_injured
- total_days_injured
- season_minutes_played
- season_games_played
- season_matches_in_squad
- total_minutes_played
- total_games_played
- dob
- height_cm
- weight_kg
- nationality
- work_rate
- pace
- physic
- fifa_rating
- position
- age
- cumulative_minutes_played
- cumulative_games_played
- minutes_per_game_prev_seasons
- avg_days_injured_prev_seasons
- avg_games_per_season_prev_seasons
- bmi
- work_rate_numeric
- position_numeric
- significant_injury_prev_season
- cumulative_days_injured
- season_days_injured_prev_season

In [3]:
import pandas as pd

# Load the dataset
file_path = '/appearances.csv'
df = pd.read_csv(file_path)

# Summary stats
total_rows = df.shape[0]
total_columns = df.shape[1]
column_names = df.columns.tolist()
data_types = df.dtypes
missing_values = df.isnull().sum()
sample_values = df.head(1).to_dict(orient='records')[0]

# Print summary
print("FIFA Players Dataset Summary")
print(f"Total Rows: {total_rows}")
print(f"Total Columns: {total_columns}\n")

print(" Column Details:")
for col in column_names:
    print(f"- {col}")
print("\n Column Breakdown:")
for col in column_names:
    print(f"{col}:")
    print(f"  - Data Type: {data_types[col]}")
    print(f"  - Missing Values: {missing_values[col]}")
    print(f"  - Sample Value: {sample_values.get(col, 'N/A')}\n")

FIFA Players Dataset Summary
Total Rows: 819975
Total Columns: 13

 Column Details:
- appearance_id
- game_id
- player_id
- player_club_id
- player_current_club_id
- date
- player_name
- competition_id
- yellow_cards
- red_cards
- goals
- assists
- minutes_played

 Column Breakdown:
appearance_id:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: 2231978_38004

game_id:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 2231978

player_id:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 38004

player_club_id:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 853

player_current_club_id:
  - Data Type: int64
  - Missing Values: 0
  - Sample Value: 235

date:
  - Data Type: object
  - Missing Values: 0
  - Sample Value: 2012-07-03

player_name:
  - Data Type: object
  - Missing Values: 6
  - Sample Value: Aurélien Joachim

competition_id:
  - Data Type: object
  - Missing Values: 1
  - Sample Value: CLQ

yellow_cards:
  - Data Type: float64
  - Missing Values: 1
  - Sample Value: 0.0

red_cards:
  - Data Type: float64
  - Missing Values: 1
  - Sample Value: 0.0

goals:
  - Data Type: float64
  - Missing Values: 1
  - Sample Value: 2.0

assists:
  - Data Type: float64
  - Missing Values: 1
  - Sample Value: 0.0

minutes_played:
  - Data Type: float64
  - Missing Values: 1
  - Sample Value: 90.0

**DATA CLEANING -WEEK 2**

In [4]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('/fifa_players.csv')

# Strip whitespace from column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Drop completely empty rows
df.dropna(how='all', inplace=True)

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Convert date columns
if 'birth_date' in df.columns:
    df['birth_date'] = pd.to_datetime(df['birth_date'], errors='coerce')

# Convert numeric columns
numeric_cols = [
    'age', 'height_cm', 'weight_kgs', 'overall_rating', 'potential',
    'value_euro', 'wage_euro', 'international_reputation(1-5)',
    'weak_foot(1-5)', 'skill_moves(1-5)', 'release_clause_euro',
    'national_rating', 'national_jersey_number', 'crossing', 'finishing',
    'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve',
    'freekick_accuracy', 'long_passing', 'ball_control', 'acceleration',
    'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power',
    'jumping', 'stamina', 'strength', 'long_shots', 'aggression',
    'interceptions', 'positioning', 'vision', 'penalties', 'composure',
    'marking', 'standing_tackle', 'sliding_tackle'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# Fill missing categorical values
categorical_cols = [
    'name', 'full_name', 'positions', 'nationality', 'preferred_foot',
    'body_type', 'national_team', 'national_team_position'
]

for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

# Optional: Normalize currency columns (e.g., convert to millions)
for col in ['value_euro', 'wage_euro', 'release_clause_euro']:
    if col in df.columns:
        df[col] = df[col] / 1e6  # Convert to millions

#  now Saving cleaned data
df.to_csv('fifa_players_cleaned.csv', index=False)

In [6]:
df = pd.read_csv('fifa_players_cleaned.csv')

In [7]:
df.describe()

,age,height_cm,weight_kgs,overall_rating,potential,value_euro,wage_euro,international_reputation(1-5),weak_foot(1-5),skill_moves(1-5),...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
count,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17699.000000,17708.000000,17954.000000,17954.000000,17954.000000,...,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000
mean,25.565445,174.946921,75.301047,66.240169,71.430935,2.479280,0.009902,1.111674,2.945695,2.361034,...,46.852456,55.816531,46.657959,49.857302,53.406260,48.357302,58.680183,47.162861,47.733040,45.705915
std,4.705708,14.029449,7.083684,6.963730,6.131339,5.687014,0.021996,0.392168,0.663691,0.763223,...,19.429337,17.394047,20.754649,19.694311,14.156038,15.810844,11.625541,20.037346,21.674973,21.285812
min,17.000000,152.400000,49.900000,47.000000,48.000000,0.010000,0.001000,1.000000,1.000000,1.000000,...,3.000000,11.000000,3.000000,2.000000,10.000000,5.000000,12.000000,3.000000,2.000000,3.000000
25%,22.000000,154.940000,69.900000,62.000000,67.000000,0.325000,0.001000,1.000000,3.000000,2.000000,...,32.000000,44.000000,26.000000,38.000000,44.000000,38.000000,51.000000,30.000000,27.000000,24.000000
50%,25.000000,175.260000,74.800000,66.000000,71.000000,0.700000,0.003000,1.000000,3.000000,2.000000,...,51.000000,59.000000,52.000000,55.000000,55.000000,49.000000,60.000000,52.500000,55.000000,52.000000
75%,29.000000,185.420000,79.800000,71.000000,75.000000,2.100000,0.009000,1.000000,3.000000,3.000000,...,62.000000,69.000000,64.000000,64.000000,64.000000,60.000000,67.000000,64.000000,66.000000,64.000000
max,46.000000,205.740000,110.200000,94.000000,95.000000,110.500000,0.565000,5.000000,5.000000,5.000000,...,94.000000,95.000000,92.000000,95.000000,94.000000,92.000000,96.000000,94.000000,93.000000,90.000000

In [9]:
# column names
df.columns

# number of rows and columns
df.shape

# Get data types
df.dtypes

# overall summary
df.info()

# statistical summary
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17954 entries, 0 to 17953
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           17954 non-null  object
 1   full_name                      17954 non-null  object
 2   birth_date                     17954 non-null  object
 3   age                            17954 non-null  int64
 4   height_cm                      17954 non-null  float64
 5   weight_kgs                     17954 non-null  float64
 6   positions                      17954 non-null  object
 7   nationality                    17954 non-null  object
 8   overall_rating                 17954 non-null  int64
 9   potential                      17954 non-null  int64
 10  value_euro                     17699 non-null  float64
 11  wage_euro                      17708 non-null  float64
 12  preferred_foot                 17954 non-null  object
 13  international_reputation(1-5)  17954 non-null  int64
 14  weak_foot(1-5)                 17954 non-null  int64
 15  skill_moves(1-5)               17954 non-null  int64
 16  body_type                      17954 non-null  object
 17  release_clause_euro            16117 non-null  float64
 18  national_team                  17954 non-null  object
 19  national_rating                857 non-null    float64
 20  national_team_position         17954 non-null  object
 21  national_jersey_number         857 non-null    float64
 22  crossing                       17954 non-null  int64
 23  finishing                      17954 non-null  int64
 24  heading_accuracy               17954 non-null  int64
 25  short_passing                  17954 non-null  int64
 26  volleys                        17954 non-null  int64
 27  dribbling                      17954 non-null  int64
 28  curve                          17954 non-null  int64
 29  freekick_accuracy              17954 non-null  int64
 30  long_passing                   17954 non-null  int64
 31  ball_control                   17954 non-null  int64
 32  acceleration                   17954 non-null  int64
 33  sprint_speed                   17954 non-null  int64
 34  agility                        17954 non-null  int64
 35  reactions                      17954 non-null  int64
 36  balance                        17954 non-null  int64
 37  shot_power                     17954 non-null  int64
 38  jumping                        17954 non-null  int64
 39  stamina                        17954 non-null  int64
 40  strength                       17954 non-null  int64
 41  long_shots                     17954 non-null  int64
 42  aggression                     17954 non-null  int64
 43  interceptions                  17954 non-null  int64
 44  positioning                    17954 non-null  int64
 45  vision                         17954 non-null  int64
 46  penalties                      17954 non-null  int64
 47  composure                      17954 non-null  int64
 48  marking                        17954 non-null  int64
 49  standing_tackle                17954 non-null  int64
 50  sliding_tackle                 17954 non-null  int64
dtypes: float64(7), int64(35), object(9)
memory usage: 7.0+ MB

,age,height_cm,weight_kgs,overall_rating,potential,value_euro,wage_euro,international_reputation(1-5),weak_foot(1-5),skill_moves(1-5),...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
count,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17699.000000,17708.000000,17954.000000,17954.000000,17954.000000,...,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000,17954.000000
mean,25.565445,174.946921,75.301047,66.240169,71.430935,2.479280,0.009902,1.111674,2.945695,2.361034,...,46.852456,55.816531,46.657959,49.857302,53.406260,48.357302,58.680183,47.162861,47.733040,45.705915
std,4.705708,14.029449,7.083684,6.963730,6.131339,5.687014,0.021996,0.392168,0.663691,0.763223,...,19.429337,17.394047,20.754649,19.694311,14.156038,15.810844,11.625541,20.037346,21.674973,21.285812
min,17.000000,152.400000,49.900000,47.000000,48.000000,0.010000,0.001000,1.000000,1.000000,1.000000,...,3.000000,11.000000,3.000000,2.000000,10.000000,5.000000,12.000000,3.000000,2.000000,3.000000
25%,22.000000,154.940000,69.900000,62.000000,67.000000,0.325000,0.001000,1.000000,3.000000,2.000000,...,32.000000,44.000000,26.000000,38.000000,44.000000,38.000000,51.000000,30.000000,27.000000,24.000000
50%,25.000000,175.260000,74.800000,66.000000,71.000000,0.700000,0.003000,1.000000,3.000000,2.000000,...,51.000000,59.000000,52.000000,55.000000,55.000000,49.000000,60.000000,52.500000,55.000000,52.000000
75%,29.000000,185.420000,79.800000,71.000000,75.000000,2.100000,0.009000,1.000000,3.000000,3.000000,...,62.000000,69.000000,64.000000,64.000000,64.000000,60.000000,67.000000,64.000000,66.000000,64.000000
max,46.000000,205.740000,110.200000,94.000000,95.000000,110.500000,0.565000,5.000000,5.000000,5.000000,...,94.000000,95.000000,92.000000,95.000000,94.000000,92.000000,96.000000,94.000000,93.000000,90.000000

Appearance dataset cleaning

In [10]:
# Step 1: Import necessary libraries
import pandas as pd
import numpy as np

# Step 2: Load the dataset
# Replace 'appearance_data.csv' with your actual file name
df = pd.read_csv('/appearances.csv')

# Step 3: Basic overview of the dataset
print("Dataset Overview:\n")
print(df.info())
print("\nFirst 5 rows:")
print(df.head())

# Step 4: Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Step 5: Handle missing values
# Fill missing text fields with 'Unknown'
df['player_name'].fillna('Unknown', inplace=True)

# Fill missing numeric fields with 0
numeric_cols = ['yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']
df[numeric_cols] = df[numeric_cols].fillna(0)

# Step 6: Convert data types
# Convert 'date' column to datetime
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Ensure IDs are integers
id_cols = ['appearance_id', 'game_id', 'player_id', 'player_club_id', 'player_current_club_id', 'competition_id']
df[id_cols] = df[id_cols].astype('Int64')

# Step 7: Remove duplicates
before = df.shape[0]
df.drop_duplicates(inplace=True)
after = df.shape[0]
print(f"\nRemoved {before - after} duplicate rows.")

# Step 8: Handle invalid or impossible values
# Replace negative minutes, goals, or cards with 0
invalid_cols = ['yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']
for col in invalid_cols:
    df[col] = df[col].apply(lambda x: max(x, 0))

# Step 9: Check for any remaining anomalies
print("\nSummary after cleaning:")
print(df.describe())

# Step 10: Save cleaned dataset (optional)
df.to_csv('appearance_data_cleaned.csv', index=False)
print("\n Cleaned dataset saved as 'appearance_data_cleaned.csv'")

Dataset Overview:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           object
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    object
 6   player_name             object
 7   competition_id          object
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), object(4)
memory usage: 169.3+ MB
None

First 5 rows:
    appearance_id  game_id  player_id  player_club_id  player_current_club_id  \
0   2231978_38004  2231978      38004             853                     235
1   2233748_79232  2233748      79232            8841                    2698
2   2234413_42792  2234413      42792            6251                     465
3   2234418_73333  2234418      73333            1274                    6646
4  2234421_122011  2234421     122011             195                    3008

         date       player_name competition_id  yellow_cards  red_cards  \
0  2012-07-03  Aurélien Joachim            CLQ             0          0
1  2012-07-05    Ruslan Abyshov            ELQ             0          0
2  2012-07-05       Sander Puri            ELQ             0          0
3  2012-07-05   Vegar Hedenstad            ELQ             0          0
4  2012-07-05  Markus Henriksen            ELQ             0          0

   goals  assists  minutes_played
0      2        0              90
1      0        0              90
2      0        0              45
3      0        0              90
4      0        1              90

Missing values per column:
appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               6
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

/tmp/ipython-input-1217363386.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['player_name'].fillna('Unknown', inplace=True)

ValueError: invalid literal for int() with base 10: 'CLQ'

Data cleaning for appearance dataset

In [12]:
import pandas as pd
import numpy as np


df = pd.read_csv('/appearances.csv') # Load the dataset


print("Before cleaning:\n")#  Basic info
print(df.info())

#  Fix missing values
# Use direct assignment (avoids chained assignment warning)
df['player_name'] = df['player_name'].fillna('Unknown')


numeric_cols = ['yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']# Fill numeric columns with 0
df[numeric_cols] = df[numeric_cols].fillna(0)

# Converting  'date' to datetime safely
df['date'] = pd.to_datetime(df['date'], errors='coerce')

#  Convert ID columns properly
id_cols = ['appearance_id', 'game_id', 'player_id', 'player_club_id', 'player_current_club_id', 'competition_id']

# Check which columns have non-numeric data
for col in id_cols:
    # Try converting to numeric, non-convertible values become NaN
    df[col] = pd.to_numeric(df[col], errors='coerce')

# (Optional): Fill NaN IDs with -1 to mark them as invalid
df[id_cols] = df[id_cols].fillna(-1).astype('Int64')

#  Remove duplicates from dataset
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"\nRemoved {before - after} duplicate rows.")

#  now Removing invalid numeric values (e.g., negative goals)
for col in numeric_cols:
    df[col] = df[col].apply(lambda x: max(x, 0))

# Summary after cleaning the dataset
print("\nAfter cleaning:\n")
print(df.info())
print("\nSummary statistics:\n")
print(df.describe())

#  now saving the cleaned data to csv file
df.to_csv('appearance_data_cleaned.csv', index=False)
print("\nCleaned dataset saved as 'appearance_data_cleaned.csv'")

Before cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           object
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    object
 6   player_name             object
 7   competition_id          object
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), object(4)
memory usage: 169.3+ MB
None

Removed 0 duplicate rows.

After cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           Int64
 1   game_id                 Int64
 2   player_id               Int64
 3   player_club_id          Int64
 4   player_current_club_id  Int64
 5   date                    datetime64[ns]
 6   player_name             object
 7   competition_id          Int64
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: Int64(6), datetime64[ns](1), int64(5), object(1)
memory usage: 179.1+ MB
None

Summary statistics:

       appearance_id         game_id      player_id  player_club_id  \
count      1706806.0       1706806.0      1706806.0       1706806.0
mean            -1.0  3166096.010633  209974.548513     3138.289598
min             -1.0       2211607.0           10.0             1.0
25%             -1.0      2589007.25        58402.0           289.0
50%             -1.0       3080787.0       149577.0           826.0
75%             -1.0       3621597.0       306668.0          2441.0
max             -1.0       4572898.0      1380876.0        110302.0
std              0.0    665119.62142  194400.813706      8315.81539

       player_current_club_id                           date  competition_id  \
count               1706806.0                        1706806       1706806.0
mean              3991.235147  2019-01-03 08:03:23.124667392            -1.0
min                      -1.0            2012-07-03 00:00:00            -1.0
25%                     331.0            2015-10-20 00:00:00            -1.0
50%                     903.0            2019-01-04 00:00:00            -1.0
75%                    2696.0            2022-04-02 00:00:00            -1.0
max                  110302.0            2025-04-10 00:00:00            -1.0
std              10847.056601                            NaN             0.0

       yellow_cards     red_cards         goals       assists  minutes_played
count  1.706806e+06  1.706806e+06  1.706806e+06  1.706806e+06    1.706806e+06
mean   1.472329e-01  3.783090e-03  9.589432e-02  7.549540e-02    6.906125e+01
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    1.000000e+00
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    4.500000e+01
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    9.000000e+01
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00    9.000000e+01
max    2.000000e+00  1.000000e+00  6.000000e+00  6.000000e+00    1.480000e+02
std    3.653799e-01  6.139039e-02  3.309349e-01  2.855614e-01    2.999313e+01

Cleaned dataset saved as 'appearance_data_cleaned.csv'

In [14]:
import pandas as pd

# Load the dataset
file_path = '/game_events.csv'
df = pd.read_csv(file_path)

# Summary stats
total_rows = df.shape[0]
total_columns = df.shape[1]
column_names = df.columns.tolist()
data_types = df.dtypes
missing_values = df.isnull().sum()
sample_values = df.head(1).to_dict(orient='records')[0]

# Print summary
print("FIFA Players Dataset Summary")
print(f"Total Rows: {total_rows}")
print(f"Total Columns: {total_columns}\n")
print(" Column Details:")
for col in column_names:
    print(f"- {col}")

FIFA Players Dataset Summary
Total Rows: 1035043
Total Columns: 10

 Column Details:
- game_event_id
- date
- game_id
- minute
- type
- club_id
- player_id
- description
- player_in_id
- player_assist_id

DATA CLEANING FOR GAME EVENTS DATASETS
{dataset has some non-integer numeric values (like NaN or decimals) in the supposed integer ID columns (for example, "player_id", "club_id", etc.).
When we try to convert them to Int64, pandas complains because it can’t safely cast float → int if there are invalid entries.}

In [18]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df = pd.read_csv('/game_events.csv')

# Step 2: Basic Overview
print("Before cleaning:\n")
print(df.info())
print("\nFirst 5 rows:\n", df.head())

# Step 3: Handle Missing Values
# Fill missing text columns with 'Unknown'
text_cols = ['type', 'description']
for col in text_cols:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

# Step 4: Convert 'date' column to datetime
if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Step 5: Convert ID columns safely
id_cols = ['game_event_id', 'game_id', 'club_id', 'player_id', 'player_in_id', 'player_assist_id']

for col in id_cols:
    if col in df.columns:
        # Convert to numeric, replace non-numeric with NaN
        df[col] = pd.to_numeric(df[col], errors='coerce')
        # Fill NaN with -1, but keep as float to avoid casting issues
        df[col] = df[col].fillna(-1)

# Step 6: Handle minute column
if 'minute' in df.columns:
    df['minute'] = pd.to_numeric(df['minute'], errors='coerce').fillna(0)
    # Ensure realistic range (0–130)
    df.loc[(df['minute'] < 0) | (df['minute'] > 130), 'minute'] = np.nan

# Step 7: Remove duplicates
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"\nRemoved {before - after} duplicate rows.")

# Step 8: Check for remaining missing values
print("\nMissing values after cleaning:")
print(df.isnull().sum())

# Step 9: Dataset summary
print("\nSummary after cleaning:")
print(df.describe(include='all'))

# Step 10: Save cleaned file
df.to_csv('game_events_cleaned.csv', index=False)
print("\n Cleaned dataset saved as 'game_events_cleaned.csv'")

Before cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035043 entries, 0 to 1035042
Data columns (total 10 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   game_event_id     1035043 non-null  object
 1   date              1035043 non-null  object
 2   game_id           1035043 non-null  int64
 3   minute            1035043 non-null  int64
 4   type              1035043 non-null  object
 5   club_id           1035043 non-null  int64
 6   player_id         1035043 non-null  int64
 7   description       947716 non-null   object
 8   player_in_id      497678 non-null   float64
 9   player_assist_id  156759 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 79.0+ MB
None

First 5 rows:
                       game_event_id        date  game_id  minute  \
0  2f41da30c471492e7d4a984951671677  2012-08-05  2211607      77
1  a72f7186d132775f234d3e2f7bc0ed5b  2012-08-05  2211607      77
2  b2d721eaed4692a5c59a92323689ef18  2012-08-05  2211607       3
3  aef768899cedac0c9a650980219075a2  2012-08-05  2211607      53
4  5d6d9533023057b6619ecd145a038bbe  2012-08-05  2211607      74

            type  club_id  player_id  \
0          Cards      610       4425
1          Cards      383      33210
2          Goals      383      36500
3          Goals      383      36500
4  Substitutions      383      36500

                                         description  player_in_id  \
0               1. Yellow card  , Mass confrontation           NaN
1               1. Yellow card  , Mass confrontation           NaN
2  , Header, 1. Tournament Goal Assist: , Corner,...           NaN
3  , Right-footed shot, 2. Tournament Goal Assist...           NaN
4                                     , Not reported       49499.0

   player_assist_id
0               NaN
1               NaN
2           56416.0
3          146258.0
4               NaN

Removed 0 duplicate rows.

Missing values after cleaning:
game_event_id           0
date                    0
game_id                 0
minute              15129
type                    0
club_id                 0
player_id               0
description             0
player_in_id            0
player_assist_id        0
dtype: int64

Summary after cleaning:
        game_event_id                           date       game_id  \
count    1.035043e+06                        1035043  1.035043e+06
unique            NaN                            NaN           NaN
top               NaN                            NaN           NaN
freq              NaN                            NaN           NaN
mean     6.843082e+25  2019-04-10 16:57:09.923587072  3.232167e+06
min     -1.000000e+00            2012-07-03 00:00:00  2.211607e+06
25%     -1.000000e+00            2015-12-10 00:00:00  2.609666e+06
50%     -1.000000e+00            2019-08-06 00:00:00  3.203637e+06
75%     -1.000000e+00            2022-08-31 00:00:00  3.840071e+06
max      7.082885e+31            2025-04-10 00:00:00  4.572898e+06
std      6.961951e+28                            NaN  6.800742e+05

              minute           type       club_id     player_id description  \
count   1.019914e+06        1035043  1.035043e+06  1.035043e+06     1035043
unique           NaN              4           NaN           NaN        8498
top              NaN  Substitutions           NaN           NaN  , Tactical
freq             NaN         498454           NaN           NaN      293274
mean    6.275217e+01            NaN  4.956375e+03  2.346498e+05         NaN
min     1.000000e+00            NaN  1.000000e+00  1.000000e+01         NaN
25%     4.600000e+01            NaN  3.470000e+02  6.600800e+04         NaN
50%     6.700000e+01            NaN  9.870000e+02  1.754490e+05         NaN
75%     8.000000e+01            NaN  3.137000e+03  3.410920e+05         NaN
max     1.200000e+02            NaN  1.224220e+05  1.378362e+06         NaN
std     2.247553e+01            NaN  1.182225e+04  2.120239e+05         NaN

        player_in_id  player_assist_id
count   1.035043e+06      1.035043e+06
unique           NaN               NaN
top              NaN               NaN
freq             NaN               NaN
mean    1.351743e+05      3.204716e+04
min    -1.000000e+00     -1.000000e+00
25%    -1.000000e+00     -1.000000e+00
50%    -1.000000e+00     -1.000000e+00
75%     2.055030e+05     -1.000000e+00
max     1.390649e+06      1.340495e+06
std     2.171661e+05      1.071347e+05

 Cleaned dataset saved as 'game_events_cleaned.csv'

In [19]:
import pandas as pd

# Load the dataset
file_path = '/transfers.csv'
df = pd.read_csv(file_path)

# Summary stats
total_rows = df.shape[0]
total_columns = df.shape[1]
column_names = df.columns.tolist()
data_types = df.dtypes
missing_values = df.isnull().sum()
sample_values = df.head(1).to_dict(orient='records')[0]

# Print summary
print("FIFA Players Dataset Summary")
print(f"Total Rows: {total_rows}")
print(f"Total Columns: {total_columns}\n")
print(" Column Details:")
for col in column_names:
    print(f"- {col}")

FIFA Players Dataset Summary
Total Rows: 79646
Total Columns: 10

 Column Details:
- player_id
- transfer_date
- transfer_season
- from_club_id
- to_club_id
- from_club_name
- to_club_name
- transfer_fee
- market_value_in_eur
- player_name

cleaning for injury dataset

In [26]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df = pd.read_csv('/injury.csv')

# Step 2: Quick overview
print("Before Cleaning:\n")
print(df.info())
print("\nFirst 5 rows:\n", df.head())

# Step 3: Convert date column to datetime
df['dob'] = pd.to_datetime(df['dob'], errors='coerce')

# Step 4: Handle missing values

# Fill missing categorical (object) columns
df['position'] = df['position'].fillna('Unknown')

# Fill numeric columns with appropriate strategies
num_cols_mean = ['pace', 'physic']  # few missing, can use mean
for col in num_cols_mean:
    df[col] = df[col].fillna(df[col].mean())

# Columns with large missing data: fill with 0 (represents unavailable previous data)
large_missing_cols = [
    'cumulative_minutes_played', 'cumulative_games_played', 'minutes_per_game_prev_seasons',
    'avg_days_injured_prev_seasons', 'avg_games_per_season_prev_seasons',
    'significant_injury_prev_season', 'cumulative_days_injured',
    'season_days_injured_prev_season'
]
df[large_missing_cols] = df[large_missing_cols].fillna(0)

# Fill missing position_numeric (use median for balance)
df['position_numeric'] = df['position_numeric'].fillna(df['position_numeric'].median())

# Step 5: Handle invalid or inconsistent values

# Ensure no negative numbers in gameplay/injury stats
cols_to_check = [
    'season_days_injured', 'total_days_injured', 'season_minutes_played',
    'season_games_played', 'season_matches_in_squad', 'total_minutes_played',
    'total_games_played', 'age', 'height_cm', 'weight_kg', 'fifa_rating', 'bmi'
]
for col in cols_to_check:
    df[col] = df[col].apply(lambda x: np.nan if x < 0 else x)

# Step 6: Drop duplicates if any
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"\nRemoved {before - after} duplicate rows.")

# Step 7: Recheck missing values
print("\nMissing values after cleaning:")
print(df.isnull().sum())

# Step 8: Clean text columns (trim spaces, standardize)
df['nationality'] = df['nationality'].str.strip()
df['work_rate'] = df['work_rate'].str.strip().str.title()
df['position'] = df['position'].str.strip().str.title()

# Step 9: Verify numeric data types
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Step 10: Final dataset summary
print("\nAfter Cleaning:\n")
print(df.describe(include='all'))

# Step 11: Save cleaned dataset
df.to_csv('fifa_players_injury_cleaned.csv', index=False)
print("\n Cleaned dataset saved as 'fifa_players_injury_cleaned.csv'")

Before Cleaning:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   p_id2                              1301 non-null   object
 1   start_year                         1301 non-null   int64
 2   season_days_injured                1301 non-null   int64
 3   total_days_injured                 1301 non-null   int64
 4   season_minutes_played              1301 non-null   float64
 5   season_games_played                1301 non-null   int64
 6   season_matches_in_squad            1301 non-null   int64
 7   total_minutes_played               1301 non-null   float64
 8   total_games_played                 1301 non-null   int64
 9   dob                                1301 non-null   object
 10  height_cm                          1301 non-null   float64
 11  weight_kg                          1301 non-null   float64
 12  nationality                        1301 non-null   object
 13  work_rate                          1301 non-null   object
 14  pace                               1206 non-null   float64
 15  physic                             1206 non-null   float64
 16  fifa_rating                        1301 non-null   float64
 17  position                           1299 non-null   object
 18  age                                1301 non-null   int64
 19  cumulative_minutes_played          697 non-null    float64
 20  cumulative_games_played            697 non-null    float64
 21  minutes_per_game_prev_seasons      685 non-null    float64
 22  avg_days_injured_prev_seasons      697 non-null    float64
 23  avg_games_per_season_prev_seasons  697 non-null    float64
 24  bmi                                1301 non-null   float64
 25  work_rate_numeric                  1301 non-null   float64
 26  position_numeric                   1299 non-null   float64
 27  significant_injury_prev_season     697 non-null    float64
 28  cumulative_days_injured            697 non-null    float64
 29  season_days_injured_prev_season    697 non-null    float64
dtypes: float64(18), int64(7), object(5)
memory usage: 305.1+ KB
None

First 5 rows:
             p_id2  start_year  season_days_injured  total_days_injured  \
0   aaronconnolly        2019                   13                 161
1   aaronconnolly        2020                   71                 161
2  aaroncresswell        2016                   95                 226
3  aaroncresswell        2018                   87                 226
4  aaroncresswell        2019                   35                 226

   season_minutes_played  season_games_played  season_matches_in_squad  \
0                 1312.0                   24                       28
1                  836.0                   17                       28
2                 2247.0                   26                       27
3                 1680.0                   20                       27
4                 2870.0                   31                       31

   total_minutes_played  total_games_played         dob  ...  \
0                2148.0                  41  2000-01-28  ...
1                2148.0                  41  2000-01-28  ...
2               13368.0                 149  1989-12-15  ...
3               13368.0                 149  1989-12-15  ...
4               13368.0                 149  1989-12-15  ...

   cumulative_games_played  minutes_per_game_prev_seasons  \
0                      NaN                            NaN
1                     24.0                      54.666667
2                      NaN                            NaN
3                     26.0                      86.423077
4                     46.0                      85.369565

  avg_days_injured_prev_seasons avg_games_per_season_prev_seasons        bmi  \
0                           NaN                               NaN  24.613627
1                          13.0                              24.0  24.613627
2                           NaN                               NaN  22.396079
3                          95.0                              26.0  22.396079
4                          91.0                              23.0  22.396079

   work_rate_numeric  position_numeric significant_injury_prev_season  \
0                2.5               2.0                            NaN
1                2.5               2.0                            0.0
2                3.5               1.0                            NaN
3                3.5               1.0                            0.0
4                3.5               1.0                            0.0

   cumulative_days_injured  season_days_injured_prev_season
0                      NaN                              NaN
1                    161.0                             13.0
2                      NaN                              NaN
3                    226.0                             95.0
4                    452.0                             87.0

[5 rows x 30 columns]

Removed 0 duplicate rows.

Missing values after cleaning:
p_id2                                0
start_year                           0
season_days_injured                  0
total_days_injured                   0
season_minutes_played                0
season_games_played                  0
season_matches_in_squad              0
total_minutes_played                 0
total_games_played                   0
dob                                  0
height_cm                            0
weight_kg                            0
nationality                          0
work_rate                            0
pace                                 0
physic                               0
fifa_rating                          0
position                             0
age                                  0
cumulative_minutes_played            0
cumulative_games_played              0
minutes_per_game_prev_seasons        0
avg_days_injured_prev_seasons        0
avg_games_per_season_prev_seasons    0
bmi                                  0
work_rate_numeric                    0
position_numeric                     0
significant_injury_prev_season       0
cumulative_days_injured              0
season_days_injured_prev_season      0
dtype: int64

After Cleaning:

            p_id2   start_year  season_days_injured  total_days_injured  \
count        1301  1301.000000          1301.000000         1301.000000
unique        604          NaN                  NaN                 NaN
top     bendavies          NaN                  NaN                 NaN
freq           24          NaN                  NaN                 NaN
mean          NaN  2018.099923            79.050730          260.710992
min           NaN  2016.000000             0.000000            3.000000
25%           NaN  2017.000000            24.000000          111.000000
50%           NaN  2018.000000            49.000000          210.000000
75%           NaN  2019.000000           103.000000          370.000000
max           NaN  2020.000000           702.000000         2398.000000
std           NaN     1.384810            84.578169          202.741896

        season_minutes_played  season_games_played  season_matches_in_squad  \
count             1301.000000          1301.000000              1301.000000
unique                    NaN                  NaN                      NaN
top                       NaN                  NaN                      NaN
freq                      NaN                  NaN                      NaN
mean              1483.156034            19.509608                25.089931
min                  0.000000             0.000000                 1.000000
25%                612.000000            10.000000                19.000000
50%               1440.000000            21.000000                28.000000
75%               2311.000000            29.000000                33.000000
max               3610.000000            38.000000                54.000000
std               1014.013920            11.099727                10.157698

        total_minutes_played  total_games_played  \
count            1301.000000         1301.000000
unique                   NaN                 NaN
top                      NaN                 NaN
freq                     NaN                 NaN
mean             5533.593390           71.638739
min                 0.000000            0.000000
25%              2012.000000           31.000000
50%              5023.000000           69.000000
75%              8387.000000          107.000000
max             16768.000000          179.000000
std              4095.421082           46.854260

                                  dob  ...  cumulative_games_played  \
count                            1301  ...              1301.000000
unique                            NaN  ...                      NaN
top                               NaN  ...                      NaN
freq                              NaN  ...                      NaN
mean    1991-12-15 11:24:01.660261376  ...                28.544197
min               1979-12-05 00:00:00  ...                 0.000000
25%               1989-05-24 00:00:00  ...                 0.000000
50%               1991-12-07 00:00:00  ...                 6.000000
75%               1994-10-06 00:00:00  ...                36.000000
max               2002-06-27 00:00:00  ...               508.000000
std                               NaN  ...                53.282936

        minutes_per_game_prev_seasons avg_days_injured_prev_seasons  \
count                     1301.000000                   1301.000000
unique                            NaN                           NaN
top                               NaN                           NaN
freq                              NaN                           NaN
mean                        39.247682                     42.592533
min                          0.000000                      0.000000
25%                          0.000000                      0.000000
50%                         35.653061                     11.000000
75%                         80.666667                     67.000000
max                         95.000000                    702.000000
std                         39.421337                     65.395214

       avg_games_per_season_prev_seasons          bmi  work_rate_numeric  \
count                        1301.000000  1301.000000        1301.000000
unique                               NaN          NaN                NaN
top                                  NaN          NaN                NaN
freq                                 NaN          NaN                NaN
mean                           11.760623    23.039310           3.346272
min                             0.000000    18.792451           2.500000
25%                             0.000000    22.093170           3.000000
50%                             5.000000    23.074830           3.500000
75%                            24.000000    23.947116           3.500000
max                            38.000000    28.525475           4.000000
std                            12.936179     1.470255           0.392971

        position_numeric significant_injury_prev_season  \
count        1301.000000                    1301.000000
unique               NaN                            NaN
top                  NaN                            NaN
freq                 NaN                            NaN
mean            1.823982                       0.120676
min             0.000000                       0.000000
25%             1.000000                       0.000000
50%             2.000000                       0.000000
75%             3.000000                       0.000000
max             3.000000                       1.000000
std             0.998727                       0.325876

        cumulative_days_injured  season_days_injured_prev_season
count               1301.000000                      1301.000000
unique                      NaN                              NaN
top                         NaN                              NaN
freq                        NaN                              NaN
mean                 421.281322                        43.544965
min                    0.000000                         0.000000
25%                    0.000000                         0.000000
50%                   75.000000                         9.000000
75%                  459.000000                        55.000000
max                 7590.000000                       702.000000
std                  872.003776                        73.851007

[11 rows x 30 columns]

 Cleaned dataset saved as 'fifa_players_injury_cleaned.csv'

GOING THROUGH 'fifa_players_injury_cleaned.csv' (after cleaning)

In [27]:


import pandas as pd

# Step 1: Load the cleaned CSV file
df = pd.read_csv('fifa_players_injury_cleaned.csv')

# Step 2: Show first few rows
print(" First 5 Rows of the Dataset:")
print(df.head(), "\n")

# Step 3: Show info about columns and data types
print(" Dataset Info:")
print(df.info(), "\n")

# Step 4: Show missing values count
print(" Missing Values in Each Column:")
print(df.isnull().sum(), "\n")

# Step 5: Describe numeric and categorical columns
print(" Statistical Summary (including all columns):")
print(df.describe(include='all'))

 First 5 Rows of the Dataset:
            p_id2  start_year  season_days_injured  total_days_injured  \
0   aaronconnolly        2019                   13                 161
1   aaronconnolly        2020                   71                 161
2  aaroncresswell        2016                   95                 226
3  aaroncresswell        2018                   87                 226
4  aaroncresswell        2019                   35                 226

   season_minutes_played  season_games_played  season_matches_in_squad  \
0                 1312.0                   24                       28
1                  836.0                   17                       28
2                 2247.0                   26                       27
3                 1680.0                   20                       27
4                 2870.0                   31                       31

   total_minutes_played  total_games_played         dob  ...  \
0                2148.0                  41  2000-01-28  ...
1                2148.0                  41  2000-01-28  ...
2               13368.0                 149  1989-12-15  ...
3               13368.0                 149  1989-12-15  ...
4               13368.0                 149  1989-12-15  ...

   cumulative_games_played  minutes_per_game_prev_seasons  \
0                      0.0                       0.000000
1                     24.0                      54.666667
2                      0.0                       0.000000
3                     26.0                      86.423077
4                     46.0                      85.369565

  avg_days_injured_prev_seasons avg_games_per_season_prev_seasons        bmi  \
0                           0.0                               0.0  24.613627
1                          13.0                              24.0  24.613627
2                           0.0                               0.0  22.396079
3                          95.0                              26.0  22.396079
4                          91.0                              23.0  22.396079

   work_rate_numeric  position_numeric significant_injury_prev_season  \
0                2.5               2.0                            0.0
1                2.5               2.0                            0.0
2                3.5               1.0                            0.0
3                3.5               1.0                            0.0
4                3.5               1.0                            0.0

   cumulative_days_injured  season_days_injured_prev_season
0                      0.0                              0.0
1                    161.0                             13.0
2                      0.0                              0.0
3                    226.0                             95.0
4                    452.0                             87.0

[5 rows x 30 columns]

 Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   p_id2                              1301 non-null   object
 1   start_year                         1301 non-null   int64
 2   season_days_injured                1301 non-null   int64
 3   total_days_injured                 1301 non-null   int64
 4   season_minutes_played              1301 non-null   float64
 5   season_games_played                1301 non-null   int64
 6   season_matches_in_squad            1301 non-null   int64
 7   total_minutes_played               1301 non-null   float64
 8   total_games_played                 1301 non-null   int64
 9   dob                                1301 non-null   object
 10  height_cm                          1301 non-null   float64
 11  weight_kg                          1301 non-null   float64
 12  nationality                        1301 non-null   object
 13  work_rate                          1301 non-null   object
 14  pace                               1301 non-null   float64
 15  physic                             1301 non-null   float64
 16  fifa_rating                        1301 non-null   float64
 17  position                           1301 non-null   object
 18  age                                1301 non-null   int64
 19  cumulative_minutes_played          1301 non-null   float64
 20  cumulative_games_played            1301 non-null   float64
 21  minutes_per_game_prev_seasons      1301 non-null   float64
 22  avg_days_injured_prev_seasons      1301 non-null   float64
 23  avg_games_per_season_prev_seasons  1301 non-null   float64
 24  bmi                                1301 non-null   float64
 25  work_rate_numeric                  1301 non-null   float64
 26  position_numeric                   1301 non-null   float64
 27  significant_injury_prev_season     1301 non-null   float64
 28  cumulative_days_injured            1301 non-null   float64
 29  season_days_injured_prev_season    1301 non-null   float64
dtypes: float64(18), int64(7), object(5)
memory usage: 305.1+ KB
None

 Missing Values in Each Column:
p_id2                                0
start_year                           0
season_days_injured                  0
total_days_injured                   0
season_minutes_played                0
season_games_played                  0
season_matches_in_squad              0
total_minutes_played                 0
total_games_played                   0
dob                                  0
height_cm                            0
weight_kg                            0
nationality                          0
work_rate                            0
pace                                 0
physic                               0
fifa_rating                          0
position                             0
age                                  0
cumulative_minutes_played            0
cumulative_games_played              0
minutes_per_game_prev_seasons        0
avg_days_injured_prev_seasons        0
avg_games_per_season_prev_seasons    0
bmi                                  0
work_rate_numeric                    0
position_numeric                     0
significant_injury_prev_season       0
cumulative_days_injured              0
season_days_injured_prev_season      0
dtype: int64

 Statistical Summary (including all columns):
            p_id2   start_year  season_days_injured  total_days_injured  \
count        1301  1301.000000          1301.000000         1301.000000
unique        604          NaN                  NaN                 NaN
top     bendavies          NaN                  NaN                 NaN
freq           24          NaN                  NaN                 NaN
mean          NaN  2018.099923            79.050730          260.710992
std           NaN     1.384810            84.578169          202.741896
min           NaN  2016.000000             0.000000            3.000000
25%           NaN  2017.000000            24.000000          111.000000
50%           NaN  2018.000000            49.000000          210.000000
75%           NaN  2019.000000           103.000000          370.000000
max           NaN  2020.000000           702.000000         2398.000000

        season_minutes_played  season_games_played  season_matches_in_squad  \
count             1301.000000          1301.000000              1301.000000
unique                    NaN                  NaN                      NaN
top                       NaN                  NaN                      NaN
freq                      NaN                  NaN                      NaN
mean              1483.156034            19.509608                25.089931
std               1014.013920            11.099727                10.157698
min                  0.000000             0.000000                 1.000000
25%                612.000000            10.000000                19.000000
50%               1440.000000            21.000000                28.000000
75%               2311.000000            29.000000                33.000000
max               3610.000000            38.000000                54.000000

        total_minutes_played  total_games_played         dob  ...  \
count            1301.000000         1301.000000        1301  ...
unique                   NaN                 NaN         588  ...
top                      NaN                 NaN  1993-06-22  ...
freq                     NaN                 NaN           9  ...
mean             5533.593390           71.638739         NaN  ...
std              4095.421082           46.854260         NaN  ...
min                 0.000000            0.000000         NaN  ...
25%              2012.000000           31.000000         NaN  ...
50%              5023.000000           69.000000         NaN  ...
75%              8387.000000          107.000000         NaN  ...
max             16768.000000          179.000000         NaN  ...

        cumulative_games_played  minutes_per_game_prev_seasons  \
count               1301.000000                    1301.000000
unique                      NaN                            NaN
top                         NaN                            NaN
freq                        NaN                            NaN
mean                  28.544197                      39.247682
std                   53.282936                      39.421337
min                    0.000000                       0.000000
25%                    0.000000                       0.000000
50%                    6.000000                      35.653061
75%                   36.000000                      80.666667
max                  508.000000                      95.000000

       avg_days_injured_prev_seasons avg_games_per_season_prev_seasons  \
count                    1301.000000                       1301.000000
unique                           NaN                               NaN
top                              NaN                               NaN
freq                             NaN                               NaN
mean                       42.592533                         11.760623
std                        65.395214                         12.936179
min                         0.000000                          0.000000
25%                         0.000000                          0.000000
50%                        11.000000                          5.000000
75%                        67.000000                         24.000000
max                       702.000000                         38.000000

                bmi  work_rate_numeric  position_numeric  \
count   1301.000000        1301.000000       1301.000000
unique          NaN                NaN               NaN
top             NaN                NaN               NaN
freq            NaN                NaN               NaN
mean      23.039310           3.346272          1.823982
std        1.470255           0.392971          0.998727
min       18.792451           2.500000          0.000000
25%       22.093170           3.000000          1.000000
50%       23.074830           3.500000          2.000000
75%       23.947116           3.500000          3.000000
max       28.525475           4.000000          3.000000

       significant_injury_prev_season  cumulative_days_injured  \
count                     1301.000000              1301.000000
unique                            NaN                      NaN
top                               NaN                      NaN
freq                              NaN                      NaN
mean                         0.120676               421.281322
std                          0.325876               872.003776
min                          0.000000                 0.000000
25%                          0.000000                 0.000000
50%                          0.000000                75.000000
75%                          0.000000               459.000000
max                          1.000000              7590.000000

        season_days_injured_prev_season
count                       1301.000000
unique                              NaN
top                                 NaN
freq                                NaN
mean                          43.544965
std                           73.851007
min                            0.000000
25%                            0.000000
50%                            9.000000
75%                           55.000000
max                          702.000000

[11 rows x 30 columns]

In [28]:
# Install required libraries first (run in your terminal or notebook)
# pip install tweepy textblob

import tweepy
from textblob import TextBlob
import pandas as pd

# --- STEP 1: Twitter API Authentication ---
# Replace with your own API credentials from https://developer.x.com/
api_key = "R9MsYnb2qx6RmPiKVlIyeP04e"
api_secret = "UWABZaqWf79eap9MwZ4Pb2Dp9HhpLxnTd5bMZOxHcJSoYJ1yeQ"
access_token = "1981621856299032576-eEhbPqMhyZlmGEOLqJniBYDviD2cvc"
access_token_secret = "a0OcMr2SA7j91jT5hWTAIFMM09irq1D1CJYUxCrkPVnB4"

# Authenticate with Tweepy
auth = tweepy.OAuth1UserHandler(api_key, api_secret, access_token, access_token_secret)
api = tweepy.API(auth)

# --- STEP 2: Search Tweets ---
# Example: analyzing sentiment for a football player, e.g., "Lionel Messi"
query = "Lionel Messi -filter:retweets"
tweets = tweepy.Cursor(api.search_tweets, q=query, lang="en", tweet_mode='extended').items(100)

data = []
for tweet in tweets:
    text = tweet.full_text
    sentiment = TextBlob(text).sentiment.polarity  # range: -1 (negative) to +1 (positive)
    data.append({"tweet": text, "sentiment": sentiment})

# --- STEP 3: Create DataFrame ---
df = pd.DataFrame(data)

# --- STEP 4: Calculate average sentiment ---
average_sentiment = df['sentiment'].mean()

print("Average Sentiment for 'Lionel Messi':", average_sentiment)
print("\nSample Tweets and Sentiment:\n", df.head())

# --- STEP 5: Save results to CSV (optional) ---
df.to_csv("player_sentiment.csv", index=False)

Forbidden: 403 Forbidden
453 - You currently have access to a subset of X API V2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.x.com/en/portal/product

In [29]:
pip install tweepy

Requirement already satisfied: tweepy in /usr/local/lib/python3.12/dist-packages (4.16.0)
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from tweepy) (3.3.1)
Requirement already satisfied: requests<3,>=2.27.0 in /usr/local/lib/python3.12/dist-packages (from tweepy) (2.32.4)
Requirement already satisfied: requests-oauthlib<3,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tweepy) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27.0->tweepy) (2025.10.5)

In [30]:
import tweepy


bearer_token = 'AAAAAAAAAAAAAAAAAAAAAKL%2B4wEAAAAAZXL6a5drPRH0kbOqbS%2FPYUnOl5o%3DNWr1m6SRoo3VAjaFi1SiagAgBroBdaWqkcegkBXhPBiQtDN1mL'

# Set up client
client = tweepy.Client(bearer_token=bearer_token)

# Example: Search recent tweets
query = 'fifa players'
response = client.search_recent_tweets(query=query, max_results=10)

# Print tweet texts
for tweet in response.data:
    print(tweet.text)

RT @iDiskiTimes: "It will be difficult for all the clubs in the league because every player sees that a coach is giving opportunities to th…
RT @iDiskiTimes: "It will be difficult for all the clubs in the league because every player sees that a coach is giving opportunities to th…
RT @iDiskiTimes: "It will be difficult for all the clubs in the league because every player sees that a coach is giving opportunities to th…
@Lwae88 @AfricaFactsZone Lool how do u even talk like this and u think to urself that yh, I made sense. 😂😂. Nothing to do with age. These football players are verified by fifa and that alone is good for the players
RT @SivanJohn_: Those 7 affected players? Yep, they’re still Malaysians in the eyes of the law; their passports are valid, no question abou…
@albsolrev @BarRed321 @eddiegibbs Our latest PL trophy has acquired a  bunch of glory hunting fools.
Klopp would have hated these new "fans" that think "Winning is the only thing that matters" &amp; slags of players.
Klopp said Football isn't FIFA &amp; if you can't support us at our worst then don't support us at all
@Staf9 @nocontextfm1 This! It feels like the other stuff was updated for the sake of an update or making it console friendly or/and targeting FIFA players for streams.
Those 7 affected players? Yep, they’re still Malaysians in the eyes of the law; their passports are valid, no question about that.

But if you ask FIFA, the answer comes with a fine print: they are Malaysians, just not eligible to play for Malaysia.

Happy Friday, folks!
"It will be difficult for all the clubs in the league because every player sees that a coach is giving opportunities to the players."

AmaZulu FC coach Arthur Zwane has discussed how Bafana Bafana's FIFA World Cup qualification could make things "difficult" for the clubs. https://t.co/FoUUQwSNco
@jokicgoatC @AjaxFik Like Harland said Messi deserved the 2023 balon dor though he didn’t
You think majority of players done feat fifa and uefa as an organization?
Only few speak up against their corruption and they’re hated for that.